/* =====================================================================
   SÉANCE IMPACT 60 (format 45 minutes) — FICHIER DE CONTENU
   C'est le SEUL fichier à modifier pour créer un nouvel atelier.
   Tout ce qui suit « window.IMPACT60 = » doit rester du JSON strict.
   Mode d'emploi : MODELE_IMPACT60.md
   ===================================================================== */
window.IMPACT60 = {
  "meta": {
    "id": "acceleration-b2-v6",
    "titre": "Accélération",
    "niveau": "B2",
    "duree": 45,
    "titreSeance": "Aller plus vite… ou mieux travailler ?",
    "objectif": "Aujourd'hui, vous apprenez à <strong>donner votre avis sur une idée pour « aller plus vite » au travail</strong> : dire ce qui est bien, dire le problème, proposer une solution. En 1 minute, sans chercher vos mots.",
    "video": {
      "url": "https://youtu.be/9cO5bDqQKMM",
      "titre": "Est-il vrai que tout va toujours plus vite ? (ARTE)",
      "duree": "25 min"
    },
    "plusLoin": [
      {
        "label": "Regarder le film en entier (25 min)",
        "url": "https://youtu.be/9cO5bDqQKMM"
      },
      {
        "label": "Atelier complet sur ce film (16 extraits, questions, vocabulaire)",
        "url": "https://orionside.github.io/Atelier_Formation_Francais/Atelier_Acceleration_B2/"
      }
    ]
  },
  "sujet": {
    "lieu": "Réunion d'équipe",
    "qui": "Votre responsable",
    "dit": "« Avec ce nouvel outil d'intelligence artificielle, nous allons faire nos rapports deux fois plus vite. »",
    "vous": "Vous aimez l'idée. Mais vous voyez un problème : il faudra tout vérifier.",
    "consigne": "Donnez votre avis.",
    "perso": {
      "question": "Dans votre entreprise, on veut aller plus vite pour…",
      "exemple": "ex. : recruter, livrer un projet, répondre aux clients",
      "phrase": "En réunion, quelqu'un propose d'aller plus vite pour : {x}. Vous voyez l'intérêt, mais aussi un problème."
    },
    "plan": [
      {
        "titre": "Ce qui est bien",
        "aide": "C'est vrai que…"
      },
      {
        "titre": "Le problème",
        "aide": "Le problème, c'est que…"
      },
      {
        "titre": "Un exemple",
        "aide": "Prenons un exemple concret : …"
      },
      {
        "titre": "Ma proposition",
        "aide": "L'idée n'est pas de…, mais de…"
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "Je ne savais pas comment commencer",
    "Je ne savais pas comment relier mes idées",
    "Je n'étais pas sûr·e de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "Plus rapide… mais plus long !",
      "debut": 355,
      "fin": 447,
      "pourquoi": "On gagne du temps… mais on le perd ailleurs. C'est l'idée de votre sujet du jour.",
      "devine": "Une femme va au travail en voiture. Elle va <strong>3 fois plus vite</strong> qu'à pied. Mais son trajet est <strong>plus long</strong> qu'avant. Pourquoi, à votre avis ? Répondez à voix haute, en une phrase.",
      "questions": [
        {
          "q": "Pourquoi son trajet est-il plus long qu'avant ?",
          "options": [
            "Il y a plus d'embouteillages.",
            "Elle habite beaucoup plus loin de son travail.",
            "Elle travaille plus d'heures."
          ],
          "bonne": 1,
          "explication": "Avec la voiture, les gens habitent plus loin de la ville. La distance est <strong>5 à 7 fois plus grande</strong>."
        },
        {
          "q": "Selon le film, pourquoi manquons-nous de temps ?",
          "options": [
            "Nous faisons beaucoup plus de choses qu'avant.",
            "Les machines sont trop lentes.",
            "Nous travaillons moins bien qu'avant."
          ],
          "bonne": 0,
          "explication": "Nous allons plus vite, mais nous faisons beaucoup plus de choses : plus de trajets, plus d'objets, plus d'informations."
        }
      ],
      "trous": [
        {
          "avant": "Conséquence directe, la distance entre le domicile et le travail ne cesse de",
          "apres": ".",
          "aide": "= devenir plus longue",
          "reponses": [
            "s'allonger",
            "s allonger",
            "sallonger"
          ],
          "solution": "s'allonger"
        },
        {
          "avant": "Ce qu'il n'avait pas",
          "apres": ", c'est l'avènement du consumérisme.",
          "aide": "= ne pas imaginer à l'avance",
          "reponses": [
            "vu venir"
          ],
          "solution": "vu venir"
        }
      ],
      "difficile": {
        "debut": 443.38,
        "fin": 446.97,
        "texte": "Ici, la voix parle vite et les mots se collent : « ce qu'il n'avait pas vu venir » se dit presque comme un seul mot. <strong>Ne pas voir venir quelque chose</strong> = ne pas l'imaginer à l'avance."
      }
    },
    {
      "id": "B",
      "titre": "Faut-il ralentir ?",
      "debut": 1341,
      "fin": 1383,
      "pourquoi": "Le sociologue refuse une idée simple, puis explique pourquoi. Vous allez faire la même chose dans votre réponse.",
      "devine": "On demande à un sociologue : « Pour avoir moins de stress, faut-il ralentir ? » À votre avis, que répond-il : oui, non, ça dépend ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Pour le sociologue, faut-il ralentir ?",
          "options": [
            "Oui, toujours.",
            "Non : ralentir n'est pas la bonne solution.",
            "Oui, mais seulement le week-end."
          ],
          "bonne": 1,
          "explication": "Il dit : « Si l'accélération est le problème, alors la réponse devrait être le ralentissement. <strong>Mais je pense que c'est une erreur.</strong> »"
        },
        {
          "q": "Quels exemples donne le sociologue ? (des cas où la lenteur est mauvaise)",
          "options": [
            "Les trains et les avions.",
            "Les réunions et les e-mails.",
            "Le médecin des urgences, les pompiers, une connexion internet lente."
          ],
          "bonne": 2,
          "explication": "Personne ne veut un médecin des urgences ou des pompiers lents, ni une connexion internet lente."
        }
      ],
      "trous": [
        {
          "avant": "Si l'accélération est le problème, alors la réponse",
          "apres": "être le ralentissement.",
          "aide": "verbe « devoir » au conditionnel",
          "reponses": [
            "devrait"
          ],
          "solution": "devrait"
        },
        {
          "avant": "L'accélération est",
          "apres": "quand elle mène à l'aliénation.",
          "aide": "= très mauvaise",
          "reponses": [
            "nefaste"
          ],
          "solution": "néfaste"
        }
      ],
      "difficile": {
        "debut": 1346.8,
        "fin": 1353.19,
        "texte": "Écoutez « Mais je pense que c'est une erreur ». La voix <strong>monte</strong> sur « pense », puis <strong>descend</strong> sur « erreur ». Cette mélodie montre que la personne est sûre de son avis. Vous allez l'utiliser dans votre réponse."
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour donner un exemple",
      "forme": "Prenons un exemple concret : …",
      "film": {
        "texte": "<strong>Prenons un exemple concret</strong> pour bien comprendre.",
        "t": 367,
        "debut": 367.54,
        "fin": 369.85,
        "contour": [
          -0.1,
          0.2,
          0.6,
          1.5,
          1.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2.1,
          2.6,
          3.4,
          4.1,
          6.0,
          6.6,
          6.7,
          6.8,
          6.9,
          6.8,
          6.4,
          5.9,
          5.5,
          4.4,
          3.5,
          3.4,
          3.1,
          2.7,
          2.4,
          0.9,
          0.5,
          0.3,
          -0.3,
          -0.5,
          -0.3,
          1.5,
          1.9,
          1.7,
          1.2,
          0.8,
          0.4,
          -0.1,
          -0.5,
          -0.9,
          -1.2,
          -1.6,
          -2.0,
          -2.1,
          -2.2,
          -2.3,
          -2.3,
          -2.4,
          -2.4,
          -2.5,
          -2.5,
          -2.6,
          -2.6,
          -2.6,
          -2.3,
          -2.2,
          -2.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.3,
          -5.2,
          -5.2,
          -5.1,
          -5.3,
          -5.6,
          -5.8,
          -6.1,
          -6.5,
          -6.7,
          -6.9,
          -6.7,
          -6.5,
          -6.3,
          -6.1,
          -5.9,
          -5.7,
          -6.5,
          -7.0,
          -7.5,
          -7.5,
          -6.9,
          -6.4,
          -5.8,
          -5.2,
          -4.6,
          -4.1,
          -3.5,
          -4.0,
          -4.7,
          -5.0,
          -8.1,
          -8.4,
          -8.8,
          -8.8
        ],
        "etendue": 14.7
      },
      "exemple": "Prenons un exemple concret : la semaine dernière, j'ai reçu plus de deux cents e-mails.",
      "detect": [
        "prenons un exemple",
        "prenons l exemple",
        "prenons le cas"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour dire ce qui ne va pas",
      "forme": "Le problème, c'est que…",
      "film": {
        "texte": "Mais <strong>le problème, c'est que</strong> l'automobile n'a pas seulement accéléré nos déplacements. Elle nous a poussés à réorganiser complètement nos villes.",
        "t": 382,
        "debut": 382.18,
        "fin": 390.19,
        "contour": [
          6.8,
          7.9,
          6.4,
          6.0,
          4.7,
          1.0,
          -2.0,
          1.7,
          2.8,
          2.4,
          -0.6,
          -0.9,
          3.4,
          8.3,
          6.4,
          4.6,
          2.2,
          -0.2,
          -1.1,
          1.3,
          0.8,
          2.2,
          1.8,
          1.0,
          -0.5,
          -1.9,
          2.6,
          5.6,
          3.0,
          -1.4,
          -2.6,
          -3.2,
          -3.5,
          -3.1,
          -2.7,
          -0.5,
          3.4,
          3.4,
          2.4,
          1.4,
          0.4,
          -0.6,
          -1.4,
          -2.3,
          0.8,
          1.1,
          -2.5,
          -4.9,
          -4.9,
          -3.5,
          -2.1,
          -2.0,
          2.6,
          1.3,
          -4.3,
          -0.6,
          3.0,
          1.5,
          -0.3,
          -0.2,
          -1.5,
          -1.3,
          -1.1,
          -3.0,
          -4.7,
          -4.4,
          -4.1,
          -3.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.6,
          0.3,
          1.0,
          0.4,
          0.8,
          1.0,
          1.1,
          5.4,
          4.0,
          4.2,
          4.3,
          0.8,
          -1.9,
          1.6,
          3.1,
          2.8,
          -0.2,
          -0.4,
          0.1,
          -0.9,
          -2.0,
          0.3,
          0.5,
          3.2,
          6.0,
          4.2,
          1.5,
          1.0,
          2.1,
          1.0,
          -2.3,
          -4.4,
          -6.1,
          -6.7,
          -6.5,
          -9.0,
          -8.0,
          -7.0,
          -6.0,
          -5.0,
          -4.0,
          -1.3
        ],
        "etendue": 12.2
      },
      "exemple": "Le problème, c'est que l'outil ne remplace pas le contrôle : il faudra toujours vérifier.",
      "detect": [
        "le probleme c est que",
        "le probleme c est"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour annoncer une conséquence",
      "forme": "Résultat, …",
      "film": {
        "texte": "<strong>Résultat,</strong> le trajet quotidien pour se rendre au travail prend aujourd'hui plus de temps qu'auparavant.",
        "t": 418,
        "debut": 418.4,
        "fin": 423.37,
        "contour": [
          2.7,
          2.5,
          2.5,
          2.4,
          2.5,
          1.2,
          0.1,
          -0.2,
          -2.5,
          -3.8,
          -2.4,
          -1.1,
          0.3,
          0.6,
          1.0,
          0.9,
          0.7,
          0.5,
          0.4,
          0.2,
          0.1,
          0.1,
          1.3,
          3.6,
          2.7,
          1.8,
          0.9,
          -0.1,
          -1.0,
          -1.9,
          -1.7,
          0.7,
          0.8,
          0.3,
          -0.2,
          -0.7,
          -0.9,
          -2.1,
          -1.0,
          0.6,
          0.8,
          0.7,
          0.5,
          -0.1,
          -0.7,
          -1.3,
          -1.9,
          -3.2,
          -3.4,
          -1.5,
          -1.0,
          -0.6,
          -0.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.6,
          -1.5,
          -3.2,
          -3.3,
          -3.3,
          -3.4,
          -3.4,
          -3.5,
          -3.5,
          -3.6,
          -1.1,
          -0.6,
          1.0,
          1.9,
          1.7,
          1.5,
          1.4,
          1.2,
          1.1,
          0.9,
          1.0,
          0.9,
          -0.1,
          -1.3,
          0.1,
          -0.5,
          -0.9,
          -2.3,
          -3.0,
          -3.1,
          -3.2,
          -0.7,
          1.8,
          4.2,
          6.7,
          9.2,
          9.4,
          7.6,
          4.0,
          3.4,
          3.9,
          2.5,
          1.5,
          0.6,
          -0.3,
          -1.2,
          -2.1,
          -3.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -7.1,
          -7.0,
          -6.9
        ],
        "etendue": 8.6
      },
      "exemple": "Résultat, on va plus vite, mais on fait plus d'erreurs.",
      "detect": [
        "resultat"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour montrer que deux choses changent ensemble",
      "forme": "Plus…, plus… / Plus…, moins…",
      "film": {
        "texte": "<strong>Plus</strong> elles nous facilitent la vie, <strong>plus</strong> elles nous permettent de compliquer celle des autres.",
        "t": 957,
        "debut": 957.36,
        "fin": 962.21,
        "contour": [
          11.9,
          -0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          -0.0,
          8.0,
          12.0,
          12.0,
          5.8,
          -0.4,
          -0.3,
          -0.2,
          -0.6,
          -1.2,
          -2.6,
          -5.5,
          -5.8,
          5.8,
          -5.8,
          -5.8,
          -6.2,
          -3.9,
          -1.5,
          0.8,
          1.1,
          2.4,
          3.8,
          5.2,
          6.6,
          5.0,
          4.5,
          4.7,
          4.0,
          3.0,
          2.0,
          1.0,
          1.0,
          0.2,
          -3.0,
          -4.6,
          -4.8,
          -5.1,
          -5.2,
          -4.0,
          -2.1,
          -1.5,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.1,
          2.1,
          5.2,
          9.1,
          11.2,
          11.9,
          12.0,
          10.2,
          7.3,
          -7.6,
          -8.2,
          2.0,
          2.3,
          2.5,
          2.0,
          1.2,
          0.6,
          4.2,
          3.8,
          2.9,
          0.0,
          -3.7,
          -6.5,
          -5.9,
          -3.9,
          -3.7,
          -3.5,
          -3.4,
          -3.2,
          -3.0,
          -3.2,
          -1.8,
          -0.4,
          1.0,
          1.2,
          1.3,
          1.2,
          1.0,
          0.9,
          0.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -7.6,
          -7.9,
          -8.3,
          -6.2,
          -6.5
        ],
        "etendue": 19.4
      },
      "exemple": "Plus on ajoute de réunions, moins on a de temps pour travailler.",
      "detect": [
        "plus … plus",
        "plus … moins",
        "moins … plus"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour refuser une idée trop simple",
      "forme": "Si…, alors on devrait… Mais je pense que c'est une erreur.",
      "film": {
        "texte": "<strong>Si</strong> l'accélération est le problème, <strong>alors</strong> la réponse <strong>devrait</strong> être le ralentissement. <strong>Mais je pense que c'est une erreur.</strong>",
        "t": 1347,
        "debut": 1346.8,
        "fin": 1353.19,
        "contour": [
          -1.9,
          -2.3,
          0.0,
          2.3,
          4.6,
          4.0,
          2.4,
          3.9,
          3.8,
          3.6,
          3.5,
          3.0,
          2.7,
          -2.2,
          -1.4,
          -1.1,
          1.0,
          3.2,
          5.3,
          5.0,
          2.6,
          -1.6,
          -3.6,
          -4.3,
          -4.6,
          -4.9,
          -5.2,
          -5.7,
          -6.2,
          -1.8,
          2.6,
          4.2,
          4.9,
          4.1,
          3.1,
          1.8,
          0.4,
          0.4,
          0.3,
          0.2,
          -0.6,
          -0.6,
          -0.6,
          1.1,
          2.5,
          3.1,
          3.0,
          1.5,
          0.4,
          -0.6,
          -0.7,
          1.1,
          2.8,
          4.6,
          6.0,
          5.6,
          3.6,
          1.7,
          1.3,
          -1.6,
          -1.8,
          1.2,
          4.2,
          3.7,
          3.4,
          2.0,
          0.7,
          -0.7,
          -1.3,
          -2.0,
          -1.3,
          -1.5,
          -1.5,
          -2.2,
          -2.7,
          -3.2,
          -3.7,
          -4.1,
          -4.6,
          -5.1,
          -6.1,
          -7.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -1.6,
          0.8,
          2.0,
          1.7,
          4.5,
          4.2,
          3.7,
          8.2,
          8.1,
          7.6,
          6.9,
          6.2,
          4.4,
          3.0,
          1.5,
          0.7,
          0.1,
          -0.5,
          -1.8,
          -3.6,
          -4.5,
          -4.8,
          -5.2,
          -5.6,
          -7.3,
          -5.6,
          -4.0,
          -2.3,
          -2.5
        ],
        "etendue": 12.2
      },
      "exemple": "Si on veut aller plus vite, alors on devrait embaucher. Mais je pense que c'est une erreur : il faut d'abord simplifier.",
      "detect": [
        "c est une erreur",
        "ce serait une erreur"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour faire une proposition",
      "forme": "L'idée n'est pas de…, mais de…",
      "film": {
        "texte": "<strong>L'idée n'est pas de</strong> la subir, <strong>mais de</strong> la considérer comme un outil susceptible d'amplifier nos propres capacités.",
        "t": 1425,
        "debut": 1424.86,
        "fin": 1432.65,
        "contour": [
          3.0,
          5.1,
          7.0,
          7.6,
          5.7,
          3.8,
          2.0,
          0.1,
          -6.7,
          -12.0,
          -0.1,
          -0.6,
          3.6,
          3.9,
          6.3,
          9.2,
          4.1,
          0.2,
          -1.1,
          3.5,
          -0.2,
          -1.0,
          -2.5,
          -4.5,
          -2.6,
          -0.7,
          1.2,
          -1.4,
          -3.1,
          -1.6,
          1.2,
          4.3,
          4.8,
          -2.0,
          -3.7,
          -2.7,
          -1.8,
          -0.8,
          -1.0,
          -1.2,
          -0.2,
          0.7,
          1.2,
          0.2,
          1.2,
          -0.1,
          0.1,
          2.3,
          4.5,
          3.9,
          5.8,
          3.6,
          3.0,
          2.4,
          6.1,
          6.5,
          0.7,
          -2.0,
          -3.3,
          -2.8,
          -0.8,
          2.4,
          2.9,
          4.0,
          5.1,
          5.0,
          5.4,
          5.7,
          6.1,
          5.7,
          5.2,
          3.5,
          4.2,
          5.0,
          5.7,
          2.2,
          -1.0,
          -2.3,
          -3.4,
          1.1,
          1.2,
          -0.2,
          0.5,
          -0.3,
          0.4,
          1.0,
          1.7,
          0.8,
          -1.2,
          -3.7,
          -2.7,
          -1.6,
          -1.8,
          -2.2,
          -2.9,
          -3.5,
          -5.2,
          -3.4,
          -4.0,
          -4.6,
          -4.5,
          -3.2,
          -4.0,
          -4.2,
          -4.4,
          -6.2,
          -7.7,
          -8.3,
          -8.9,
          -9.5,
          -10.2,
          -10.8,
          -11.4,
          -12.0,
          -9.7,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -12.0
        ],
        "etendue": 22.6
      },
      "exemple": "L'idée n'est pas d'aller plus vite, mais de mieux choisir nos priorités.",
      "detect": [
        "l idee n est pas",
        "l idee ce n est pas"
      ]
    }
  ],
  "prononciation": {
    "intro": "En français, on n'accentue pas chaque mot. On parle par <strong>groupes de mots</strong>, et on allonge la <strong>dernière syllabe</strong> du groupe.",
    "regle": [
      "On parle par groupes de mots, pas mot par mot.",
      "La <strong>dernière syllabe</strong> du groupe est plus longue.",
      "La voix <strong>monte ↗</strong> au milieu de la phrase et <strong>descend ↘</strong> à la fin."
    ],
    "attention": "En espagnol, on dit e<strong>jem</strong>plo. En français, on dit un exemple con<strong>cret</strong> : l'accent est à la fin du groupe.",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "Pre·nons un e·xem·ple con·*cret.",
        "consigne": "Cliquez sur la syllabe la plus longue.",
        "explication": "C'est « cret » : la dernière syllabe du groupe. Pas « xem » (comme en espagnol).",
        "debut": 367.54,
        "fin": 369.85
      },
      {
        "titre": "Phrase 2",
        "phrase": "Plus elles nous fa·ci·litent la *vie, plus elles nous per·*mettent de com·pli·quer celle des *autres.",
        "consigne": "Cette phrase a 3 groupes de mots. Cliquez sur la dernière syllabe de chaque groupe (3 syllabes), puis vérifiez.",
        "explication": "« vie », « mettent » et « autres » : la fin de chaque groupe. La voix monte sur « vie » et « mettent », et descend sur « autres ».",
        "debut": 957.36,
        "fin": 962.21
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue"
      ],
      [
        "|",
        "fin d'un groupe"
      ],
      [
        "‿",
        "on enchaîne, sans pause"
      ],
      [
        "[z]",
        "on ajoute le son « z » (les autres → « lé-z-autres »)"
      ],
      [
        "[n]",
        "on ajoute le son « n » (un exemple → « un-n-exemple »)"
      ],
      [
        "[t]",
        "on ajoute le son « t » (c'est une → « c'est-t-une »)"
      ]
    ],
    "modeles": [
      {
        "texte": "Prenons‿un[n]exemple con<strong>cret</strong> ↗ | pour bien com<strong>prendre</strong> ↘",
        "t": 367,
        "debut": 367.54,
        "fin": 369.85,
        "contour": [
          -0.1,
          0.2,
          0.6,
          1.5,
          1.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2.1,
          2.6,
          3.4,
          4.1,
          6.0,
          6.6,
          6.7,
          6.8,
          6.9,
          6.8,
          6.4,
          5.9,
          5.5,
          4.4,
          3.5,
          3.4,
          3.1,
          2.7,
          2.4,
          0.9,
          0.5,
          0.3,
          -0.3,
          -0.5,
          -0.3,
          1.5,
          1.9,
          1.7,
          1.2,
          0.8,
          0.4,
          -0.1,
          -0.5,
          -0.9,
          -1.2,
          -1.6,
          -2.0,
          -2.1,
          -2.2,
          -2.3,
          -2.3,
          -2.4,
          -2.4,
          -2.5,
          -2.5,
          -2.6,
          -2.6,
          -2.6,
          -2.3,
          -2.2,
          -2.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.3,
          -5.2,
          -5.2,
          -5.1,
          -5.3,
          -5.6,
          -5.8,
          -6.1,
          -6.5,
          -6.7,
          -6.9,
          -6.7,
          -6.5,
          -6.3,
          -6.1,
          -5.9,
          -5.7,
          -6.5,
          -7.0,
          -7.5,
          -7.5,
          -6.9,
          -6.4,
          -5.8,
          -5.2,
          -4.6,
          -4.1,
          -3.5,
          -4.0,
          -4.7,
          -5.0,
          -8.1,
          -8.4,
          -8.8,
          -8.8
        ],
        "etendue": 14.7
      },
      {
        "texte": "Plus[z]elles nous facilitent la <strong>vie</strong> ↗ | plus[z]elles nous per<strong>mettent</strong> ↗ | de compliquer celle des[z]<strong>autres</strong> ↘",
        "t": 957,
        "debut": 957.36,
        "fin": 962.21,
        "contour": [
          11.9,
          -0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          -0.0,
          8.0,
          12.0,
          12.0,
          5.8,
          -0.4,
          -0.3,
          -0.2,
          -0.6,
          -1.2,
          -2.6,
          -5.5,
          -5.8,
          5.8,
          -5.8,
          -5.8,
          -6.2,
          -3.9,
          -1.5,
          0.8,
          1.1,
          2.4,
          3.8,
          5.2,
          6.6,
          5.0,
          4.5,
          4.7,
          4.0,
          3.0,
          2.0,
          1.0,
          1.0,
          0.2,
          -3.0,
          -4.6,
          -4.8,
          -5.1,
          -5.2,
          -4.0,
          -2.1,
          -1.5,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.1,
          2.1,
          5.2,
          9.1,
          11.2,
          11.9,
          12.0,
          10.2,
          7.3,
          -7.6,
          -8.2,
          2.0,
          2.3,
          2.5,
          2.0,
          1.2,
          0.6,
          4.2,
          3.8,
          2.9,
          0.0,
          -3.7,
          -6.5,
          -5.9,
          -3.9,
          -3.7,
          -3.5,
          -3.4,
          -3.2,
          -3.0,
          -3.2,
          -1.8,
          -0.4,
          1.0,
          1.2,
          1.3,
          1.2,
          1.0,
          0.9,
          0.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -7.6,
          -7.9,
          -8.3,
          -6.2,
          -6.5
        ],
        "etendue": 19.4
      },
      {
        "texte": "Si l'accélération est le pro<strong>blème</strong> ↗ | alors la réponse devrait être le ralentisse<strong>ment</strong> ↘ | Mais je <strong>pense</strong> ↗ | que c'est[t]une‿er<strong>reur</strong> ↘",
        "t": 1347,
        "debut": 1346.8,
        "fin": 1353.19,
        "contour": [
          -1.9,
          -2.3,
          0.0,
          2.3,
          4.6,
          4.0,
          2.4,
          3.9,
          3.8,
          3.6,
          3.5,
          3.0,
          2.7,
          -2.2,
          -1.4,
          -1.1,
          1.0,
          3.2,
          5.3,
          5.0,
          2.6,
          -1.6,
          -3.6,
          -4.3,
          -4.6,
          -4.9,
          -5.2,
          -5.7,
          -6.2,
          -1.8,
          2.6,
          4.2,
          4.9,
          4.1,
          3.1,
          1.8,
          0.4,
          0.4,
          0.3,
          0.2,
          -0.6,
          -0.6,
          -0.6,
          1.1,
          2.5,
          3.1,
          3.0,
          1.5,
          0.4,
          -0.6,
          -0.7,
          1.1,
          2.8,
          4.6,
          6.0,
          5.6,
          3.6,
          1.7,
          1.3,
          -1.6,
          -1.8,
          1.2,
          4.2,
          3.7,
          3.4,
          2.0,
          0.7,
          -0.7,
          -1.3,
          -2.0,
          -1.3,
          -1.5,
          -1.5,
          -2.2,
          -2.7,
          -3.2,
          -3.7,
          -4.1,
          -4.6,
          -5.1,
          -6.1,
          -7.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -1.6,
          0.8,
          2.0,
          1.7,
          4.5,
          4.2,
          3.7,
          8.2,
          8.1,
          7.6,
          6.9,
          6.2,
          4.4,
          3.0,
          1.5,
          0.7,
          0.1,
          -0.5,
          -1.8,
          -3.6,
          -4.5,
          -4.8,
          -5.2,
          -5.6,
          -7.3,
          -5.6,
          -4.0,
          -2.3,
          -2.5
        ],
        "etendue": 12.2
      }
    ],
    "etapes": [
      "Écoutez la phrase 2 fois.",
      "Parlez <strong>en même temps</strong> que la voix, 2 fois.",
      "Enregistrez-vous seul·e et comparez les courbes."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "essais": [
      {
        "duree": 90,
        "consigne": "Parlez avec vos notes.",
        "ajout": "Pour l'essai 2, ajoutez : « <strong>Le problème, c'est que…</strong> » et « <strong>Prenons un exemple concret…</strong> »."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur vous interrompt une fois. Répondez avec : « <strong>Je suis d'accord sur…, mais…</strong> »",
        "ajout": "Pour l'essai 3, ajoutez : « <strong>L'idée n'est pas de…, mais de…</strong> ». Et faites des groupes de mots : pas de pause au milieu d'un groupe."
      },
      {
        "duree": 60,
        "consigne": "Sans vos notes. Seulement l'essentiel.",
        "ajout": ""
      }
    ],
    "objections": [
      "Mais tous nos concurrents le font déjà !",
      "Le client veut une réponse plus rapide.",
      "Nous n'avons pas le budget pour faire autrement.",
      "C'est une décision de la direction."
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Répétez les 3 phrases de la mélodie avec le film, en même temps que la voix (5 minutes)."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites les 6 phrases utiles sans regarder (bouton « Vérifier sans regarder »)."
    },
    {
      "jour": "Jour 3",
      "tache": "Dites votre phrase de la semaine dans une vraie réunion ou un vrai appel."
    },
    {
      "jour": "Jour 4",
      "tache": "Enregistrez 1 minute sur le sujet du jour et envoyez-la à votre formateur."
    }
  ],
  "voix": {
    "neuronale": "fr-FR-RemyMultilingualNeural",
    "dossiers": {
      "formateur": "audio/formateur/",
      "neuronale": "audio/neuronal/"
    }
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Choisissez le sujet ensemble pendant la discussion libre (champ « Mon sujet »). Enregistrement d'1 minute, sans correction."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute le film",
        "role": "Faites deviner avant chaque écoute. Le « passage difficile » se réécoute seul, phrase par phrase."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Film → répétition → phrase personnelle à voix haute. Faites adapter l'exemple au secteur de l'apprenant."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Une seule cible : l'accent en fin de groupe. Syllabes à cliquer, puis shadowing et comparaison des courbes."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Jouez l'interlocuteur. À l'essai 2, lisez une objection. Retour entre les essais : 2 points au maximum."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même sujet qu'au début. Commentez les 3 chiffres avec l'apprenant."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une réunion réelle, une date."
      }
    ],
    "notes": [
      "Séance prévue pour 45 minutes, après 10 à 15 minutes de discussion libre.",
      "Incitez l'apprenant à se corriger (« Pardon ? », « Où est l'accent ? ») plutôt que de donner la bonne forme.",
      "Les chiffres de la page sont indicatifs. Pour une mesure complète, passez l'enregistrement au script mesure_oral.py.",
      "Voix : les phrases du film sont jouées dans le lecteur YouTube officiel. Les exemples « Au travail » utilisent audio/formateur/p1.mp3… (votre voix), sinon audio/neuronal/p1.mp3…",
      "La vitesse « un peu plus lent » (0,9×) n'apparaît que si YouTube la propose pour cette vidéo. On ne descend jamais plus bas : la voix deviendrait artificielle."
    ]
  }
};
