window.GLP_UX_TARGETS=[
 [
  {q:'Quel sens voulez-vous conserver ?',options:['Une situation a changé entre avant et maintenant.','Deux situations actuelles sont identiques.'],feedback:'Avant et maintenant comparent deux moments. Remplacez la difficulté et le résultat par votre propre expérience.',groups:['Avant,','c’était difficile.','Maintenant,','c’est plus simple.'],focus:'Faites entendre les deux moments. Laissez une frontière entre les idées, puis gardez les mots de chaque groupe liés.',mission:'Racontez un changement dans vos achats ou votre travail. Donnez une situation avant et une situation maintenant.'},
  {q:'Que fait la personne avec « on pensait… mais… » ?',options:['Elle corrige une première idée à partir de ce qui s’est passé.','Elle confirme que sa première idée était exacte.'],feedback:'On pensait présente une attente. Mais introduit ce qui oblige à la revoir. Conservez cette différence dans votre exemple.',groups:['On pensait','que cela allait disparaître,','mais les besoins ont changé.'],focus:'Reliez les mots de « on pensait ». Rendez le contraste audible avec « mais », sans faire une pause après chaque mot.',mission:'Racontez une attente qui a changé. Dites ce que vous pensiez, puis ce que vous avez observé.'},
  {q:'Que signifie « bien au-delà » dans cette phrase ?',options:['Le changement concerne davantage que le domaine cité.','Le changement coûte forcément plus cher.'],feedback:'Au-delà élargit le domaine. Cette expression ne donne pas, à elle seule, une information sur le prix.',groups:['Ça va bien au-delà','des achats.'],focus:'Enchaînez « au-delà » comme un ensemble. La fin de groupe porte l’idée, sans accentuer chaque mot.',mission:'Présentez un changement qui touche plusieurs domaines. Expliquez ce qui dépasse le premier domaine cité.'}
 ],
 [
  {q:'À quoi servent « d’abord, ensuite, enfin » ici ?',options:['À annoncer trois points organisés.','À dire que les trois points sont synonymes.'],feedback:'Les mots organisent les points. Dans un récit, ils peuvent aussi organiser les événements : choisissez selon votre intention.',groups:['D’abord, l’intérêt.','Ensuite, la limite.','Enfin, le coût.'],focus:'Donnez une frontière audible à chaque point. Le rythme aide l’interlocuteur à suivre la liste.',mission:'Présentez un service en trois points : son intérêt, sa limite et son coût ou une autre condition.'},
  {q:'Quelle relation annonce « en revanche » ?',options:['Une différence ou une limite par rapport à la première idée.','La cause automatique de la première idée.'],feedback:'En revanche introduit une contrepartie. Ne l’utilisez pas pour remplacer parce que.',groups:['C’est pratique.','En revanche,','il faut vérifier.'],focus:'Dites « en revanche » comme une unité. La liaison dans « il faut » ne se crée pas : gardez simplement les mots dans le même groupe.',mission:'Présentez un avantage et une limite d’un service. Vérifiez ensuite l’avis de votre interlocuteur.'},
  {q:'Que permet d’affirmer « pourrait… si… » ?',options:['Un résultat est possible sous une condition.','Le résultat est déjà obtenu dans tous les cas.'],feedback:'Pourrait marque une possibilité ; si donne la condition. Conservez les deux pour éviter de promettre un résultat certain.',groups:['Cela pourrait aider,','si les conditions sont réunies.'],focus:'Gardez la condition liée à l’idée principale. La frontière sert le sens ; elle ne doit pas transformer la condition en promesse.',mission:'Proposez une amélioration possible. Précisez la condition nécessaire, puis demandez si elle est réaliste.'}
 ],
 [
  {q:'Que faut-il préserver dans ce récit ?',options:['L’ordre des événements et l’arrêt des réponses du vendeur.','L’idée que le vendeur continue à répondre après le refus.'],feedback:'D’abord et ensuite donnent l’ordre. Ne… plus indique que les réponses s’arrêtent. Une négation perdue change le récit.',groups:['D’abord, ils contactent le vendeur.','Ensuite, ils refusent.','Finalement, il ne répond plus.'],focus:'Faites entendre trois étapes. Dans le dernier groupe, conservez « ne répond plus » ; ne sacrifiez pas le sens pour aller plus vite.',mission:'Racontez une démarche en trois étapes. Dites ce qui change ou s’arrête à la fin.'},
  {q:'« Ça a l’air sérieux » suffit-il à affirmer que c’est fiable ?',options:['Non : c’est une apparence qui demande une vérification.','Oui : l’apparence garantit la fiabilité.'],feedback:'Avoir l’air décrit une impression. Mais il faut vérifier garde une distance entre cette impression et un fait confirmé.',groups:['Ça a l’air sérieux,','mais il faut vérifier.'],focus:'Dans « ça a l’air », les deux a peuvent s’enchaîner sans pause forcée. Faites ensuite entendre la réserve introduite par « mais ».',mission:'Décrivez une impression sur un document ou une annonce. Expliquez ce que vous voulez vérifier.'},
  {q:'Quel degré de certitude la phrase exprime-t-elle ?',options:['Une supposition encore non vérifiée.','Un fait démontré par une vérification.'],feedback:'J’imagine marque une supposition. Je ne l’ai pas vérifié précise sa limite. Gardez ces indices quand vous transmettez l’information.',groups:['J’imagine que c’est possible,','mais je ne l’ai pas vérifié.'],focus:'Enchaînez « je ne l’ai pas » dans un groupe compréhensible. La négation reste importante pour le sens.',mission:'Exprimez une supposition sur une situation, puis dites comment vous pourriez la vérifier.'}
 ]
];
