/* =====================================================================
   SÉANCE IMPACT 60 (format 45 minutes) — FICHIER DE CONTENU
   Atelier : Français pour débutants – Rendez-vous (Learn French with Alacarte Studio)
   Tout ce qui suit « window.IMPACT60 = » doit rester du JSON strict.
   Mode d'emploi : MODELE_IMPACT60.md
   ===================================================================== */
window.IMPACT60 = {
  "meta": {
    "id": "rendez-vous-a1-v1",
    "lien": "https://orionside.github.io/Atelier_Formation_Francais/Atelier_Rendez_Vous_A1/",
    "titre": "Rendez-vous",
    "niveau": "A1",
    "duree": 45,
    "support": {
      "le": "la vidéo",
      "du": "de la vidéo",
      "dans": "dans la vidéo",
      "Le": "La vidéo"
    },
    "titreSeance": "Se présenter… et commander au café",
    "objectif": "Aujourd'hui, vous apprenez à <strong>vous présenter</strong> (nom, nationalité, ville) et à <strong>commander et payer au café</strong>. En 1 minute, avec des phrases courtes.",
    "video": {
      "url": "https://youtu.be/HNBQOEb_O5k",
      "titre": "Français pour débutants – Rendez-vous (Learn French with Alacarte Studio)",
      "duree": "5 min"
    },
    "plusLoin": [
      {
        "label": "Regarder la vidéo en entier (5 min)",
        "url": "https://youtu.be/HNBQOEb_O5k"
      }
    ]
  },
  "sujet": {
    "lieu": "Au café, avant une réunion",
    "qui": "Une nouvelle collègue française",
    "dit": "« Bonjour ! Je m'appelle Camille. Je suis française. Et vous ? »",
    "vous": "Vous répondez : votre nom, votre nationalité, votre ville. Puis vous commandez pour vous deux, et vous payez.",
    "consigne": "Présentez-vous, puis commandez.",
    "perso": {
      "question": "Qui rencontrez-vous au café, dans votre vie ?",
      "exemple": "ex. : un client, un nouveau collègue, un voisin",
      "phrase": "Au café, vous rencontrez : {x}. Présentez-vous (nom, nationalité, ville), puis commandez et payez."
    },
    "plan": [
      {
        "titre": "Mon nom",
        "aide": "Bonjour ! Je m'appelle… Et vous ?"
      },
      {
        "titre": "Ma nationalité et ma ville",
        "aide": "Je suis espagnol(e). J'habite à…"
      },
      {
        "titre": "Je commande",
        "aide": "Un café pour moi, s'il vous plaît."
      },
      {
        "titre": "Je paie et je pars",
        "aide": "L'addition, s'il vous plaît."
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "Je ne savais pas comment commencer",
    "Je ne savais pas dire « tu » ou « vous »",
    "Je n'étais pas sûr·e de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "Bonjour ! Je suis…",
      "debut": 4.4,
      "fin": 38.74,
      "pourquoi": "Un homme et une femme se rencontrent. Ils disent leur nom, leur nationalité, leur ville et leur métier. Vous allez faire la même chose.",
      "devine": "Vous rencontrez une personne pour la première fois. Vous dites quoi ? Répondez à voix haute : 2 phrases.",
      "questions": [
        {
          "q": "L'homme est de quelle nationalité ?",
          "options": [
            "Il est hongrois.",
            "Il est français.",
            "Il est espagnol."
          ],
          "bonne": 1,
          "explication": "Il dit : « <strong>Je suis français.</strong> Et toi ? » La femme répond : « Je suis hongroise. »"
        },
        {
          "q": "Quel est le métier de la femme ?",
          "options": [
            "Elle est docteur.",
            "Elle est serveuse.",
            "Elle est professeure."
          ],
          "bonne": 2,
          "explication": "L'homme dit : « Je suis docteur. Et toi ? » Elle répond : « <strong>Je suis professeure.</strong> »"
        }
      ],
      "trous": [
        {
          "avant": "J'habite à Budapest, mais je ne",
          "apres": "pas hongrois.",
          "aide": "verbe « parler » (hablar)",
          "reponses": [
            "parle"
          ],
          "solution": "parle"
        },
        {
          "avant": "Mais moi, je parle un",
          "apres": "français.",
          "aide": "= pas beaucoup (un poco)",
          "reponses": [
            "peu"
          ],
          "solution": "peu"
        }
      ],
      "difficile": {
        "debut": 20.34,
        "fin": 24.3,
        "texte": "« J'habite à Budapest, mais je ne parle pas hongrois. » Écoutez « <strong>je ne parle pas</strong> » : pour dire non, on met <strong>ne</strong> avant le verbe et <strong>pas</strong> après. À l'oral, le « ne » est très court."
      }
    },
    {
      "id": "B",
      "titre": "Au café",
      "debut": 136.9,
      "fin": 212.4,
      "pourquoi": "Ils commandent, ils reçoivent la commande, puis ils paient et partent. Avec le serveur, on dit « vous ».",
      "devine": "Au café, le serveur arrive. Vous dites quoi pour commander un café ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Qu'est-ce qu'ils commandent ?",
          "options": [
            "Deux thés et un sandwich.",
            "Un café noir, un café long, un jus d'orange et un croissant.",
            "Une eau et un gâteau."
          ],
          "bonne": 1,
          "explication": "« Un café noir pour moi, s'il vous plaît. » — « Un café long et un jus d'orange. » Puis : « <strong>Un croissant aussi.</strong> »"
        },
        {
          "q": "Comment paient-ils ?",
          "options": [
            "Par carte.",
            "En espèces.",
            "Ils ne paient pas."
          ],
          "bonne": 1,
          "explication": "Le serveur demande : « Carte ou espèces ? » Réponse : « <strong>Espèces.</strong> » (= avec des billets et des pièces, en efectivo)."
        }
      ],
      "trous": [
        {
          "avant": "Bonjour madame. Bonjour monsieur.",
          "apres": "la carte.",
          "aide": "= je vous donne (aquí tiene)",
          "reponses": [
            "voici",
            "voila"
          ],
          "solution": "Voici"
        },
        {
          "avant": "Merci beaucoup. — Je vous en",
          "apres": ".",
          "aide": "réponse polie à « merci » (de nada)",
          "reponses": [
            "prie"
          ],
          "solution": "prie"
        }
      ],
      "difficile": {
        "debut": 198.84,
        "fin": 205.17,
        "texte": "« Carte ou espèces ? — Espèces, espèces. » Le serveur ne fait pas une phrase complète : c'est normal au café. <strong>Carte</strong> = carte bancaire. <strong>Espèces</strong> = billets et pièces. On répond avec un seul mot, ou : « Par carte, s'il vous plaît. »"
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour dire qui on est, et poser la même question à l'autre (« toi » avec un ami, « vous » au travail)",
      "forme": "Je suis… Et toi ? / Et vous ?",
      "film": {
        "texte": "<strong>Je suis Philippe. Et toi ?</strong> — Je suis Adrienne.",
        "t": 12,
        "debut": 11.42,
        "fin": 15.58,
        "contour": [
          -2.7,
          -2.7,
          -2.7,
          -3.2,
          -3.6,
          -2.3,
          -1.1,
          0.2,
          1.5,
          1.3,
          1.0,
          -0.4,
          -1.9,
          -0.5,
          0.8,
          2.2,
          3.5,
          4.9,
          4.6,
          4.3,
          3.1,
          4.4,
          4.6,
          4.2,
          3.2,
          0.6,
          0.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.7,
          -0.3,
          -1.8,
          -3.0,
          -2.6,
          -2.1,
          -1.7,
          -1.3,
          -1.4,
          -1.2,
          -0.8,
          -0.7,
          -0.3,
          -0.0,
          0.0,
          -0.5,
          -0.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1.1,
          1.1,
          1.0,
          1.8,
          2.6,
          3.5,
          4.3,
          5.1,
          5.9,
          6.5,
          7.3,
          7.4,
          6.4,
          5.3,
          4.2,
          3.2,
          2.1,
          1.1,
          0.6,
          -1.4,
          -1.8,
          1.6,
          1.5,
          1.7,
          2.0,
          1.8,
          1.3,
          0.7,
          0.1,
          -0.5,
          -1.3,
          -2.4,
          -2.5,
          -2.3,
          -2.4,
          -2.6,
          -2.7,
          -2.2,
          -2.2
        ],
        "etendue": 8.8
      },
      "exemple": "Bonjour, je suis Ana. Et vous ?",
      "detect": [
        "et toi",
        "et vous"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour dire sa nationalité (un homme : espagnol ; une femme : espagnole)",
      "forme": "Je suis espagnol. / Je suis espagnole.",
      "film": {
        "texte": "<strong>Je suis français.</strong> Et toi ? — <strong>Je suis hongroise.</strong>",
        "t": 17,
        "debut": 15.84,
        "fin": 20.73,
        "contour": [
          -6.5,
          -7.2,
          -8.2,
          -8.9,
          -8.3,
          -7.8,
          -7.2,
          -6.7,
          -6.2,
          -5.6,
          -5.9,
          -7.0,
          -7.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.4,
          -5.5,
          -5.7,
          -6.2,
          -6.4,
          -5.4,
          -4.4,
          -3.5,
          -2.5,
          -1.5,
          -1.9,
          -2.5,
          -3.2,
          -4.6,
          -5.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.9,
          -4.4,
          -5.0,
          -5.3,
          -3.9,
          -2.5,
          -1.2,
          0.2,
          0.0,
          0.4,
          0.5,
          -0.0,
          -0.2,
          0.2,
          0.5,
          0.5,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.6,
          0.6,
          0.6,
          0.6,
          1.1,
          1.7,
          2.2,
          2.8,
          3.3,
          3.9,
          4.4,
          5.9,
          7.1,
          7.4,
          7.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          4.0,
          4.6,
          5.9,
          6.9,
          7.0,
          6.2,
          4.8
        ],
        "etendue": 14.5
      },
      "exemple": "Je suis espagnole. J'habite à Madrid.",
      "detect": [
        "je suis espagnol",
        "je suis espagnole"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour demander le prénom, et le corriger poliment",
      "forme": "Comment tu t'appelles ? — Je m'appelle…",
      "film": {
        "texte": "<strong>Comment tu t'appelles ?</strong> Adriana ? Adriana ? — <strong>Non, je m'appelle Adrienne.</strong>",
        "t": 75,
        "debut": 74.18,
        "fin": 83.6,
        "contour": [
          -5.4,
          -12.0,
          -4.0,
          -4.8,
          -5.6,
          -6.3,
          -7.1,
          -7.9,
          -8.7,
          -7.9,
          -11.8,
          -8.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.2,
          -2.3,
          1.1,
          4.1,
          5.1,
          4.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -10.2,
          -9.0,
          -6.4,
          -2.5,
          1.2,
          2.0,
          2.2,
          0.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -2.5,
          -2.2,
          0.4,
          5.3,
          10.1,
          12.0,
          11.2,
          6.4,
          -0.9,
          -4.8,
          -4.0,
          -4.2,
          -2.1,
          -0.0,
          2.1,
          4.1,
          6.2,
          8.3,
          10.4,
          0.3,
          -1.5,
          -1.2,
          -1.2,
          -2.3,
          -0.4,
          1.4,
          2.7,
          4.6,
          6.1,
          4.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.6,
          2.7,
          4.4,
          5.1,
          2.0,
          -1.0,
          -1.1,
          -1.0,
          -0.9,
          -0.3,
          1.5,
          2.7,
          2.9,
          -3.4,
          -1.9,
          -0.3,
          1.2,
          1.7,
          -1.4,
          -5.9,
          -12.0
        ],
        "etendue": 19.6
      },
      "exemple": "Comment vous vous appelez ? — Je m'appelle Laura.",
      "detect": [
        "je m appelle",
        "comment tu t appelles",
        "comment vous vous appelez"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour commander au café",
      "forme": "Un café pour moi, s'il vous plaît.",
      "film": {
        "texte": "<strong>Un café noir pour moi, s'il vous plaît.</strong>",
        "t": 146,
        "debut": 145.52,
        "fin": 148.66,
        "contour": [
          -2.6,
          -2.6,
          -2.7,
          -2.7,
          -1.4,
          -0.1,
          1.2,
          2.5,
          3.8,
          3.3,
          2.9,
          2.6,
          3.0,
          3.4,
          3.9,
          4.3,
          4.7,
          4.6,
          4.4,
          3.2,
          2.4,
          1.9,
          1.6,
          1.1,
          0.5,
          0.1,
          -0.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.9,
          -5.7,
          -4.8,
          -3.7,
          -3.0,
          -3.0,
          -3.5,
          -3.8,
          -4.0
        ],
        "etendue": 10.2
      },
      "exemple": "Un thé pour moi, s'il vous plaît.",
      "detect": [
        "pour moi s il vous plait",
        "s il vous plait"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour dire que la commande est finie",
      "forme": "C'est tout ? — Oui, merci, c'est tout.",
      "film": {
        "texte": "Parfait. <strong>C'est tout ? — Oui, merci, c'est tout.</strong>",
        "t": 155,
        "debut": 154.47,
        "fin": 157.53,
        "contour": [
          -4.7,
          -4.9,
          -5.0,
          -5.4,
          -5.4,
          -5.3,
          -5.2,
          -3.0,
          -0.7,
          1.5,
          1.6,
          1.8,
          2.7,
          3.5,
          3.8,
          3.8,
          3.7,
          3.2,
          2.8,
          2.4,
          2.4,
          2.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.9,
          7.9,
          7.9,
          4.0,
          0.1,
          -0.2,
          -0.3,
          -0.3,
          -0.3,
          0.2,
          0.4,
          0.4,
          0.2,
          -0.0,
          -0.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.7,
          0.6,
          0.6,
          0.5,
          -0.0,
          -0.9,
          -1.6,
          -1.3,
          -1.0,
          -0.6,
          -0.3,
          0.0,
          -0.5,
          -0.9,
          -1.1,
          -1.8,
          -2.2,
          -2.2,
          -1.4,
          -0.8,
          -0.1,
          0.5,
          0.1,
          -0.2,
          -0.2,
          -0.2,
          -0.2,
          -0.2
        ],
        "etendue": 9.0
      },
      "exemple": "Vous voulez autre chose ? — Non merci, c'est tout.",
      "detect": [
        "c est tout"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour demander à payer (l'addition = la cuenta)",
      "forme": "L'addition, s'il vous plaît.",
      "film": {
        "texte": "<strong>L'addition, s'il vous plaît.</strong>",
        "t": 192,
        "debut": 191.0,
        "fin": 193.54,
        "contour": [
          -6.7,
          -6.7,
          -6.5,
          -6.3,
          -6.2,
          -6.0,
          -5.8,
          -5.7,
          -5.7,
          -5.7,
          -5.6,
          -5.4,
          -5.1,
          -4.7,
          -3.7,
          -2.9,
          -2.9,
          -2.3,
          -2.3,
          -2.3,
          -2.5,
          -2.9,
          -3.6,
          -3.6,
          -4.0,
          -4.5,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1.3,
          1.3,
          1.4,
          1.5,
          1.5,
          1.5,
          1.4,
          1.3,
          1.2,
          1.2,
          1.0,
          0.9,
          0.8,
          0.7,
          0.5,
          0.4,
          0.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.1,
          0.0,
          -0.0,
          -0.0,
          -0.2,
          -1.0,
          -1.1,
          -1.1,
          -1.1,
          -0.9,
          -0.6,
          -0.6,
          -0.2,
          -0.1,
          0.0,
          0.0,
          0.0,
          -0.1,
          -0.1,
          -0.4,
          -0.7,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.2,
          0.4,
          0.5,
          0.5,
          0.5,
          0.5,
          0.5,
          0.4,
          0.3,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.4,
          0.5,
          0.7,
          0.9,
          0.9,
          1.1,
          1.1,
          1.2,
          1.2,
          1.1,
          1.1
        ],
        "etendue": 7.4
      },
      "exemple": "L'addition, s'il vous plaît. Je paie par carte.",
      "detect": [
        "l addition"
      ]
    }
  ],
  "prononciation": {
    "intro": "En français, la voix <strong>monte ↗</strong> quand ce n'est pas fini : une autre information arrive, ou vous posez une question. La voix <strong>descend ↘</strong> quand c'est fini.",
    "regle": [
      "Vous donnez une information, et il y a une suite : la voix <strong>monte ↗</strong>.",
      "Vous proposez quelque chose (« Un café ? ») : la voix <strong>monte ↗</strong>.",
      "C'est la dernière information : la voix <strong>descend ↘</strong>. L'autre sait que c'est à lui de parler."
    ],
    "attention": "La dernière syllabe du mot est plus longue : Adri<strong>enne</strong>, hon<strong>groise</strong>, fran<strong>çais</strong> (en espagnol : fran<strong>cés</strong>, c'est pareil !). Attention : toutes les questions ne montent pas. Dans la vidéo, « Et toi ? » reste plat. Les flèches ↗ ↘ montrent la mélodie <strong>mesurée</strong> dans la vidéo.",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "Bon·jour, je suis A·dri·*enne, je suis hon·*groise et j'habite aus·si à Bu·da·pest.",
        "consigne": "La femme donne 3 informations. Écoutez : sur quelles syllabes la voix monte-t-elle très nettement ? Cliquez sur les 2 syllabes, puis vérifiez.",
        "explication": "La voix monte sur « -enne » et « -groise » : il y a une suite. À la fin (« Budapest »), elle ne monte plus : c'est fini.",
        "debut": 265.02,
        "fin": 272.12
      },
      {
        "titre": "Phrase 2",
        "phrase": "Je parle fran·çais, an·*glais et hon·grois.",
        "consigne": "L'homme donne une liste de 3 langues. Cliquez sur la syllabe où la voix monte, puis vérifiez.",
        "explication": "La voix monte sur « -glais » : la liste continue. Sur « hongrois », elle descend : la liste est finie.",
        "debut": 287.97,
        "fin": 291.87
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte (mesuré dans la vidéo)"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue"
      ],
      [
        "|",
        "fin d'une information"
      ],
      [
        "‿",
        "on enchaîne, sans pause"
      ]
    ],
    "modeles": [
      {
        "texte": "Un ca<strong>fé</strong> ↗ ?",
        "t": 34,
        "debut": 33.4,
        "fin": 35.9,
        "contour": [
          -3.0,
          -3.0,
          -3.0,
          -3.1,
          -3.1,
          -3.1,
          -3.2,
          -3.2,
          -3.2,
          -3.2,
          -3.2,
          -3.3,
          -3.3,
          -3.3,
          -3.3,
          -3.3,
          -3.3,
          -3.3,
          -3.3,
          -3.4,
          -3.4,
          -3.5,
          -3.5,
          -3.5,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.0,
          0.0,
          -0.1,
          -0.1,
          -0.1,
          -0.1,
          -0.1,
          -0.1,
          -0.3,
          -0.3,
          -0.5,
          -0.5,
          -0.5,
          -1.4,
          -1.4,
          -2.3,
          -2.3,
          -2.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          7.4,
          7.4,
          7.4,
          7.6,
          7.6,
          7.6,
          7.7,
          7.7,
          8.5,
          8.5,
          8.5,
          9.5,
          9.5,
          10.3,
          10.3,
          10.3,
          11.0,
          11.0,
          11.0,
          11.0,
          11.0,
          11.0,
          11.0,
          11.0,
          11.0,
          11.0,
          10.6,
          10.6,
          10.6,
          10.2,
          10.2,
          10.2,
          9.8,
          9.8,
          9.6,
          9.6,
          9.6,
          9.3,
          9.3
        ],
        "etendue": 14.3
      },
      {
        "texte": "Bon<strong>jour</strong> | je suis Adri<strong>enne</strong> ↗ | je suis hon<strong>groise</strong> ↗ | et j'habite‿aussi à Buda<strong>pest</strong>",
        "t": 266,
        "debut": 265.02,
        "fin": 272.12,
        "contour": [
          3.3,
          3.6,
          5.2,
          5.4,
          2.8,
          0.5,
          -1.9,
          -2.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1.6,
          1.8,
          1.3,
          0.7,
          0.2,
          -0.4,
          -1.3,
          -1.6,
          -1.9,
          -2.2,
          -2.2,
          -2.0,
          -1.7,
          -2.6,
          -2.7,
          -1.9,
          0.3,
          4.5,
          9.0,
          12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.0,
          -0.1,
          -0.3,
          0.2,
          0.7,
          1.2,
          0.5,
          -1.0,
          -1.9,
          -2.9,
          -3.4,
          -3.9,
          -3.8,
          1.0,
          5.7,
          8.2,
          9.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.1,
          -0.7,
          -1.9,
          -0.1,
          -0.2,
          0.5,
          4.8,
          5.5,
          3.4,
          1.6,
          0.2,
          0.9,
          1.5,
          2.2,
          1.6,
          -0.6,
          -1.4,
          -0.8,
          -1.7,
          -2.2
        ],
        "etendue": 12.2
      },
      {
        "texte": "Je parle fran<strong>çais</strong> ↗ | an<strong>glais</strong> ↗ | un peu espa<strong>gnol</strong> | mais je ne parle pas hon<strong>grois</strong> ↘",
        "t": 226,
        "debut": 225.16,
        "fin": 233.32,
        "contour": [
          -2.4,
          -4.3,
          -3.3,
          -2.3,
          -3.8,
          -5.1,
          -8.6,
          -12.0,
          -12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.9,
          1.9,
          2.2,
          3.1,
          4.1,
          4.3,
          6.9,
          9.0,
          9.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -1.7,
          -1.0,
          -0.1,
          -0.5,
          12.0,
          4.8,
          6.8,
          7.9,
          7.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.6,
          -3.0,
          -2.9,
          -7.5,
          -12.0,
          0.9,
          8.2,
          12.0,
          10.2,
          -0.2,
          -0.7,
          -1.2,
          -1.8,
          -2.3,
          -3.4,
          -3.4,
          -2.1,
          2.1,
          3.7,
          4.3,
          6.6,
          6.8,
          6.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -4.8,
          -4.9,
          -5.8,
          -4.3,
          -4.9,
          -6.1,
          -7.0,
          -7.0,
          -6.9,
          -6.0,
          -7.4,
          -9.6,
          -2.4,
          4.8,
          7.5,
          8.6,
          8.9,
          9.2,
          7.1,
          6.5,
          3.7,
          0.8,
          0.1,
          -1.2,
          -0.5,
          -2.8
        ],
        "etendue": 20.1
      },
      {
        "texte": "Je parle fran<strong>çais</strong> | an<strong>glais</strong> ↗ | et hon<strong>grois</strong> ↘",
        "t": 289,
        "debut": 287.97,
        "fin": 291.87,
        "contour": [
          -0.8,
          -0.5,
          0.0,
          -0.0,
          -0.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -1.8,
          -1.9,
          -1.9,
          -1.9,
          -1.6,
          -1.6,
          -1.7,
          -2.1,
          -2.6,
          -3.0,
          -2.8,
          -2.6,
          -2.4,
          -2.3,
          -2.1,
          -1.9,
          -1.7,
          -1.6,
          -1.6,
          -1.9,
          -2.7,
          -3.1,
          -2.5,
          -1.9,
          -1.3,
          -0.8,
          -0.2,
          0.4,
          1.0,
          1.3,
          2.0,
          3.1,
          4.1,
          5.3,
          6.3,
          6.3,
          -2.6,
          -2.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.7,
          -0.5,
          -0.2,
          -0.2,
          -0.1,
          0.0,
          -0.1,
          -0.5,
          -0.3,
          0.3,
          0.6,
          0.8,
          1.0,
          1.7,
          1.9,
          2.2,
          3.0,
          3.7,
          4.5,
          5.5,
          6.0,
          7.9,
          8.8,
          10.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1.9,
          2.0,
          2.3,
          2.3,
          2.3,
          1.5,
          0.9,
          0.7,
          0.5,
          0.3,
          0.1,
          -0.2,
          -0.5,
          -1.5,
          -2.5,
          -3.5,
          -3.2,
          -3.0,
          -3.2,
          -3.9,
          -4.8,
          -5.4
        ],
        "etendue": 9.5
      }
    ],
    "etapes": [
      "Écoutez la phrase 2 fois.",
      "Parlez <strong>en même temps</strong> que la voix, 2 fois.",
      "Enregistrez-vous seul·e et comparez les courbes."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "boutonObjection": "Question du serveur (pour le formateur)",
    "essais": [
      {
        "duree": 90,
        "consigne": "Parlez avec vos notes : votre nom, votre nationalité, votre ville, puis la commande.",
        "ajout": "Pour l'essai 2, ajoutez : « <strong>Et vous ?</strong> » et « <strong>Oui, merci, c'est tout.</strong> ». Et faites monter la voix ↗ à la fin de chaque information."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur joue le serveur et vous pose une question. Répondez.",
        "ajout": "Pour l'essai 3, finissez avec : « <strong>L'addition, s'il vous plaît.</strong> » puis « <strong>Merci, bonne journée ! Au revoir !</strong> »"
      },
      {
        "duree": 60,
        "consigne": "Sans vos notes. Seulement l'essentiel.",
        "ajout": ""
      }
    ],
    "objections": [
      "Carte ou espèces ?",
      "C'est tout ?",
      "Pardon, vous vous appelez comment ?",
      "Désolé, il n'y a plus de jus d'orange. Vous voulez autre chose ?"
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Répétez les 4 phrases de la mélodie avec la vidéo, en même temps que la voix (5 minutes)."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites les 6 phrases utiles sans regarder (bouton « Vérifier sans regarder »)."
    },
    {
      "jour": "Jour 3",
      "tache": "Présentez-vous à voix haute en 4 phrases : nom, nationalité, ville, langues. Enregistrez-vous."
    },
    {
      "jour": "Jour 4",
      "tache": "Enregistrez 1 minute : vous vous présentez et vous commandez au café. Envoyez-la à votre formateur."
    }
  ],
  "voix": {
    "moteur": "Qwen3-TTS-12Hz-1.7B-Base-8bit",
    "dossier": "audio/qwen3-tts/"
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Jouez la collègue : « Bonjour ! Je m'appelle Camille. Je suis française. Et vous ? » 1 minute, sans correction. Pour un A1, 3 à 5 phrases, c'est déjà bien."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute la vidéo",
        "role": "Dialogue joué, lent (environ 87 mots/min). Faites deviner avant chaque écoute. Le passage difficile se réécoute seul."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Moitié « se présenter » (p1, p2, p3), moitié « au café » (p4, p5, p6). Faites dire chaque phrase avec les informations réelles de l'apprenant."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Cible : la voix monte ↗ à la fin de chaque information, et descend ↘ à la fin. Syllabes à cliquer, puis parler en même temps que la voix, puis courbes."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Vous jouez la collègue, puis le serveur. À l'essai 2, lisez une question (« Question du serveur »). Retour entre les essais : 2 points au maximum."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même situation qu'au début. Commentez les 3 chiffres avec l'apprenant."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une situation réelle (un café, une réunion), une date."
      }
    ],
    "notes": [
      "Vidéo : petit film joué par des acteurs (voix humaines), pour débutants. Un Français (docteur) et une Hongroise (professeure) se rencontrent, puis vont au café ; à la fin, chaque personnage se présente seul. Débit lent (environ 87 mots/min), phrases très courtes.",
      "Tu et vous : les deux personnages se disent « tu » ; avec le serveur, tout le monde dit « vous ». Pour l'apprenant, au travail : « vous » d'abord.",
      "Blague à expliquer : Adrienne dit d'abord « J'ai 20 ans » (pour plaisanter), puis « J'ai 40 ans » dans sa présentation finale. Philippe a 60 ans, Patrice 50 ans, Olaf (le chien) 2 ans : utile pour les nombres.",
      "Extraits : chaque phrase commence 0,6 s avant le premier mot et finit 0,3 s après le dernier, puis a été retranscrite avec deux modèles Whisper (grand et petit), entière et sans ses 0,4 premières secondes : aucun mot ne manque. Dans la marge de la phrase 5, on entend aussi « Parfait ».",
      "Mélodie mesurée (pas supposée) : dans la présentation d'Adrienne, la voix monte sur « Adrienne » (+10 demi-tons) et « hongroise » (+9) ; dans la liste de Philippe, elle monte sur « français » (+3) et « anglais » (+7), puis descend sur « hongrois » (−9) ; chez Patrice, « anglais » ↗ (+4), « hongrois » ↘ (−8) ; « Un café ? » monte (+10 en fin de mot). Pas de flèche sur « Budapest » ni « espagnol » : mesure ambiguë. « Et toi ? » reste plat (0) et « Adrienne ? » (confirmation) descend (−7) : c'est pourquoi la cible n'est pas « la question monte », mais « la voix monte quand ce n'est pas fini ».",
      "Transcription : les sous-titres et la reconnaissance vocale écrivent parfois « espèce » au lieu de « espèces » (payer en espèces), « professeur » pour « professeure » (même prononciation), « en droit » ou « anglois » pour « hongrois », « La mission » pour « L'addition ». À 0:38, on appelle le chien : « Allez, Olaf ! »",
      "Support de conversation complet (11 segments, questions et focus grammaire) : à utiliser en parallèle pour la discussion ; cet atelier sert à l'entraînement oral mesuré."
    ]
  }
};
