const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');const{JSDOM,VirtualConsole}=require('/Users/toufik/impact60_mesure/tests/node_modules/jsdom');const root=path.resolve(__dirname,'..');const results=[];
for(const file of ['focus.html','atelier.html'])for(let session=1;session<=3;session++){
 const raw=fs.readFileSync(root+'/'+file,'utf8');const html=raw.replace(/<script src="([^"?]+)(?:\?[^\"]*)?"><\/script>/g,(_,f)=>'<script>'+fs.readFileSync(path.resolve(root,f),'utf8')+'</script>');const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/Not implemented/.test(e.message))errors.push(e.message)});
 const dom=new JSDOM(html,{url:'https://example.test/'+file+'?seance='+session,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.load=()=>{};}});const w=dom.window,d=w.document;
 for(let i=0;i<9;i++){
  d.querySelectorAll('.rl')[i].click();const main=d.querySelector('main');assert(main.querySelector('.stepnav'));for(const b of main.querySelectorAll('.audio-circle')){const e=w.GLP_AUDIO_CATALOGUE[b.dataset.audioId];assert(e,b.dataset.audioId);const asset=path.resolve(w.GLP_UX_AUDIO_IDS&&w.GLP_UX_AUDIO_IDS[e.id]?root:path.resolve(root,'../Atelier_GLP1_Oral_B2_v2'),e.file);assert(fs.existsSync(asset),'Chemin audio incorrect : '+asset);if(process.argv.includes('--complet'))assert(w.GLP_AUDIO_MANIFEST.clips[e.id],e.id+' MP3 manquant');}
  if(i===2){const cards=[...main.querySelectorAll('.step>.card')];assert.equal(cards.filter(x=>!x.hidden).length,1);const pager=main.querySelector('.ux-pager');pager.querySelectorAll('button')[1].click();assert(!cards[1].hidden&&cards[0].hidden);pager.querySelectorAll('button')[2].click();assert(cards.every(x=>!x.hidden));for(const q of main.querySelectorAll('.mcq')){assert(q.querySelector('.opts').hidden);q.querySelector('.oral-reveal').click();q.querySelector('.opt').click();assert(!q.querySelector('.expl').hidden);}for(const g of main.querySelectorAll('.gap-row'))assert(g.querySelector('.gap-sol').closest('[hidden]'));}
  if(i===3&&file==='focus.html'){assert.equal([...main.querySelectorAll('.pc')].filter(x=>!x.hidden).length,1);}
  if(i===3&&file==='atelier.html'){
   const cards=[...main.querySelectorAll('.ux-oral-card')];assert.equal(cards.length,3);assert.equal(cards.filter(x=>!x.hidden).length,1);
   for(const c of cards){const phases=[...c.querySelectorAll('.ux-phase')];assert.equal(phases.length,5);assert.equal(phases.filter(x=>!x.hidden).length,1);assert(phases[0].querySelector('.opts').hidden);phases[0].querySelector('button.btn').click();assert(!phases[0].querySelector('.opts').hidden);phases[0].querySelector('button.opt').click();assert(!phases[0].querySelector('.ux-feedback').hidden);for(const [j,b]of [...c.querySelectorAll('.ux-cycle>button')].entries()){b.click();assert.equal(phases.filter(x=>!x.hidden).length,1);assert(!phases[j].hidden);}assert(!phases[3].querySelector('details').open);}
  }
 }
 assert.deepEqual(errors,[]);results.push({version:file,session,views:9,errors:0});dom.window.close();
}
if(process.argv.includes('--complet')){const c=JSON.parse(fs.readFileSync(root+'/audio/catalogue.json')).entries,m=JSON.parse(fs.readFileSync(root+'/audio/qwen3-tts/manifest.json')).clips;assert.equal(c.length,Object.keys(m).length);for(const e of c){assert.equal(e.tts_text,m[e.id].tts_text);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(root+'/'+e.file)).digest('hex'),m[e.id].sha256);}}
fs.writeFileSync(root+'/tests-parcours.json',JSON.stringify(results,null,2)+'\n');console.log('54 vues, pagination, révélation des réponses, 9 boucles de 5 phases : OK.');
