/* =====================================================================
   SÉANCE IMPACT 60 (format 45 minutes) — FICHIER DE CONTENU
   Atelier : Livre ou liseuse ? | Écolo mon cul ! (ARTE)  — v2 : mélodie mesurée
   Tout ce qui suit « window.IMPACT60 = » doit rester du JSON strict.
   Mode d'emploi : MODELE_IMPACT60.md
   ===================================================================== */
window.IMPACT60 = {
  "meta": {
    "id": "livre-liseuse-b2c1-v2",
    "lien": "https://orionside.github.io/Atelier_Formation_Francais/Atelier_Livre_Liseuse_B2C1_v2/",
    "titre": "Livre ou liseuse ?",
    "niveau": "B2–C1",
    "duree": 45,
    "support": {
      "le": "la vidéo",
      "du": "de la vidéo",
      "dans": "dans la vidéo",
      "Le": "La vidéo"
    },
    "titreSeance": "« C'est vrai, sauf que… » : nuancer une idée qui semble évidente",
    "objectif": "Aujourd'hui, vous apprenez à <strong>reconnaître ce qui est vrai</strong> dans une idée, puis à <strong>la nuancer avec un argument</strong> et à <strong>proposer une solution</strong>. En 1 minute, sans chercher vos mots.",
    "video": {
      "url": "https://youtu.be/_oOwr_Z-scY",
      "titre": "Livre ou liseuse ? | Écolo mon cul ! (ARTE)",
      "duree": "11 min"
    },
    "plusLoin": [
      {
        "label": "Regarder la vidéo en entier (11 min)",
        "url": "https://youtu.be/_oOwr_Z-scY"
      }
    ]
  },
  "sujet": {
    "lieu": "En réunion d'équipe",
    "qui": "Une collègue",
    "dit": "« À partir de lundi, on passe au zéro papier : tout sur tablette. C'est plus écolo, c'est évident ! »",
    "vous": "Vous êtes d'accord sur une partie, mais ce n'est pas si simple. Reconnaissez ce qui est vrai, nuancez avec un argument, puis proposez une solution.",
    "consigne": "Répondez-lui.",
    "perso": {
      "question": "Dans votre entreprise, quelle idée « évidente » mériterait d'être nuancée ?",
      "exemple": "ex. : tout passer au cloud, changer tous les ordinateurs, faire toutes les réunions en visio",
      "phrase": "En réunion, un collègue annonce : {x}. « C'est évident ! » Reconnaissez ce qui est vrai, nuancez avec un argument, puis proposez une solution."
    },
    "plan": [
      {
        "titre": "Reconnaître",
        "aide": "C'est pas faux. / C'est vrai que…"
      },
      {
        "titre": "Nuancer",
        "aide": "…sauf que…"
      },
      {
        "titre": "Un argument",
        "aide": "Si on fait bien les comptes, …"
      },
      {
        "titre": "Proposer",
        "aide": "Il faudrait plutôt…"
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "J'ai dit « oui » ou « non », sans nuance",
    "Je n'avais pas d'argument concret",
    "Je n'étais pas sûr·e de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "« Une liseuse, c'est très matériel »",
      "debut": 228.5,
      "fin": 289,
      "pourquoi": "Un personnage croit avoir trouvé la solution. L'expert le freine, puis nuance avec des faits. C'est ce que vous allez faire.",
      "devine": "Un personnage dit : « Ce qu'il faut, c'est <strong>dématérialiser</strong> (= tout mettre en numérique). » À votre avis, une liseuse est-elle vraiment « sans matière » ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Pourquoi l'expert dit-il qu'une liseuse n'est « pas du tout dématérialisée » ?",
          "options": [
            "Parce qu'elle consomme beaucoup d'électricité.",
            "Parce qu'il faut du plastique et beaucoup de métaux pour la fabriquer.",
            "Parce qu'on ne peut pas y mettre beaucoup de livres."
          ],
          "bonne": 1,
          "explication": "« Il faut du plastique pour l'objet en lui-même », puis de l'aluminium, du cuivre, de l'indium, de l'étain… des métaux « arrachés à la terre »."
        },
        {
          "q": "Selon la vidéo, l'exploitation minière est…",
          "options": [
            "la 1re cause de déforestation dans le monde.",
            "la 3e cause de déforestation dans le monde.",
            "sans effet sur les forêts."
          ],
          "bonne": 1,
          "explication": "« L'exploitation minière représente la <strong>troisième</strong> cause de déforestation dans le monde. » Les mines obligent d'abord à « raser des forêts »."
        }
      ],
      "trous": [
        {
          "avant": "Au contraire, c'est même très très",
          "apres": ".",
          "aide": "le contraire de « dématérialisé »",
          "reponses": [
            "matériel"
          ],
          "solution": "matériel"
        },
        {
          "avant": "…l'étain, toute une",
          "apres": "de métaux plus ou moins rares.",
          "aide": "familier : = une grande quantité",
          "reponses": [
            "floppée",
            "flopée"
          ],
          "solution": "floppée"
        }
      ],
      "difficile": {
        "debut": 244.5,
        "fin": 253,
        "texte": "Une liste de métaux, très vite : « de l'aluminium, du cuivre, de l'indium, de l'étain, toute une floppée de métaux plus ou moins rares arrachés à la terre ». Pas besoin de tout retenir. Retenez l'expression utile : <strong>toute une floppée de</strong> (familier, = beaucoup de)."
      }
    },
    {
      "id": "B",
      "titre": "Liseuse + livres papier = double facture",
      "debut": 482.4,
      "fin": 552.8,
      "pourquoi": "Les personnages veulent la liseuse… et les livres papier. L'expert montre, chiffres à l'appui, que ce n'est pas si simple.",
      "devine": "Beaucoup de gens ont une liseuse. À votre avis, est-ce qu'ils arrêtent d'acheter des livres papier ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Combien d'utilisateurs de liseuses lisent <strong>seulement</strong> des livres numériques ?",
          "options": [
            "1 %",
            "40 %",
            "99 %"
          ],
          "bonne": 0,
          "explication": "« Seul 1 % des utilisateurs et utilisatrices de liseuses ne lisent que des formats numériques. » Les 99 % restants achètent aussi des livres papier."
        },
        {
          "q": "Vous prêtez un livre papier à votre colocataire, qui le lit. Selon la vidéo, son impact…",
          "options": [
            "double.",
            "ne change pas.",
            "est divisé par deux."
          ],
          "bonne": 2,
          "explication": "« Vous divisez par deux son impact environnemental », car « le livre a été fabriqué une fois, mais il a rendu son service deux fois »."
        }
      ],
      "trous": [
        {
          "avant": "Mais tu as raison, je vais faire",
          "apres": "la facture environnementale.",
          "aide": "familier : faire … = faire exploser",
          "reponses": [
            "péter"
          ],
          "solution": "péter"
        },
        {
          "avant": "Un livre en papier, ça se",
          "apres": ".",
          "aide": "on le donne à quelqu'un, qui le rend ensuite",
          "reponses": [
            "prête"
          ],
          "solution": "prête"
        }
      ],
      "difficile": {
        "debut": 503.3,
        "fin": 517.9,
        "texte": "Des pourcentages, très vite : « Seul 1 % des utilisateurs et utilisatrices de liseuses ne lisent que des formats numériques. Les 99 % restants achètent aussi des livres papier en plus des livres numériques. » Écoutez « <strong>ne</strong> lisent <strong>que</strong> » (= lisent seulement) et « les 99 % <strong>restants</strong> » (= les autres)."
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour reconnaître un point, puis nuancer",
      "forme": "C'est vrai, sauf que…",
      "film": {
        "texte": "<strong>C'est vrai, sauf que</strong> souvent ces livres ne sont lus qu'une seule fois, avant de prendre la poussière sur une étagère pendant des années. Et ça, pour le bilan environnemental, c'est pas ouf.",
        "t": 185,
        "debut": 184,
        "fin": 194.8
      },
      "exemple": "C'est vrai que la visio fait gagner du temps, sauf qu'on perd souvent les échanges informels.",
      "detect": [
        "c est vrai sauf que",
        "sauf que"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour freiner quelqu'un qui conclut trop vite",
      "forme": "Pas si vite !",
      "film": {
        "texte": "<strong>Pas si vite</strong>, champion. Une liseuse, c'est pas du tout dématérialisé. Au contraire, c'est même très très matériel.",
        "t": 236,
        "debut": 235.2,
        "fin": 242.2
      },
      "exemple": "Pas si vite : avant de tout changer, regardons d'abord les chiffres.",
      "detect": [
        "pas si vite"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour demander une comparaison honnête",
      "forme": "Il faut comparer ce qui est comparable.",
      "film": {
        "texte": "Allez, ouvrez vos manuels, on va potasser. Tout d'abord, si vous souhaitez faire un achat éclairé, <strong>il faut commencer par comparer ce qui est comparable</strong>.",
        "t": 70,
        "debut": 69.3,
        "fin": 78
      },
      "exemple": "Pour choisir entre les deux logiciels, il faut comparer ce qui est comparable : le prix, mais aussi le temps de formation.",
      "detect": [
        "comparer ce qui est comparable"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour appuyer sa nuance sur des faits",
      "forme": "Si on fait bien les comptes, …",
      "film": {
        "texte": "En fait, <strong>si on fait bien les comptes</strong>, quels que soient les indicateurs – émission de particules fines, changement climatique, utilisation des ressources minérales et métalliques ou encore écotoxicité de l'eau douce –, la fabrication d'une liseuse génère beaucoup plus d'impact que la fabrication d'un livre.",
        "t": 340,
        "debut": 339.9,
        "fin": 357
      },
      "exemple": "Si on fait bien les comptes, le nouvel outil nous coûte plus cher que l'ancien la première année.",
      "detect": [
        "si on fait bien les comptes",
        "si on fait les comptes"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour montrer que tout dépend d'une condition",
      "forme": "Plus…, plus…",
      "film": {
        "texte": "Et je rapporte le tout à la durée de vie de votre liseuse, car évidemment, <strong>plus</strong> vous la gardez longtemps, <strong>plus</strong> les coûts environnementaux seront amortis.",
        "t": 457,
        "debut": 456.4,
        "fin": 463
      },
      "exemple": "Plus on garde nos ordinateurs longtemps, plus leur coût est amorti.",
      "detect": [
        "plus on",
        "plus vous",
        "plus les"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour concéder un point, puis proposer une solution",
      "forme": "C'est pas faux… Il faudrait (plutôt)…",
      "film": {
        "texte": "<strong>C'est pas faux.</strong> Les autrices, les auteurs, les libraires, les maisons d'édition… C'est déjà pas simple de gagner sa vie avec des livres. Pour produire moins de livres neufs, <strong>il faudrait</strong> repenser toute l'industrie et ses modèles de rémunération en profondeur. Un beau chantier de société.",
        "t": 621,
        "debut": 620.3,
        "fin": 637.5
      },
      "exemple": "C'est pas faux, le papier coûte cher. Mais il faudrait plutôt réduire les impressions que tout passer sur tablette.",
      "detect": [
        "c est pas faux",
        "ce n est pas faux",
        "il faudrait"
      ]
    }
  ],
  "prononciation": {
    "intro": "Pour <strong>nuancer</strong>, on parle en deux temps : d'abord on reconnaît (« C'est vrai »), <strong>petite pause</strong>, puis on nuance (« sauf que… »). À l'oral, chaque groupe de mots se termine par une syllabe un peu plus longue. Et on fait les <strong>liaisons obligatoires</strong>.",
    "regle": [
      "Coupez votre phrase en groupes courts.",
      "Faites une petite pause <strong>avant</strong> « sauf que », « mais », « or ».",
      "Faites les liaisons obligatoires : « les auteurs » se dit « lé-<strong>z</strong>auteurs », « deux expressos » se dit « deu-<strong>z</strong>expressos »."
    ],
    "attention": "Sans la pause, votre nuance sonne comme une contradiction brutale. Les flèches ↗ ↘ montrent la mélodie <strong>mesurée</strong> dans la vidéo.",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "Qu'un ou deux *ex·pres·sos bien tassés.",
        "consigne": "Écoutez. Sur quelle syllabe entendez-vous un son [z] qui n'est pas écrit ? Cliquez dessus.",
        "explication": "« deux[z]expressos » : on entend « de-<strong>z</strong>ex-pres-sos ». Après « deux », « trois », « les », « des », la liaison est obligatoire devant une voyelle.",
        "debut": 307.8,
        "fin": 312.9
      },
      {
        "titre": "Phrase 2",
        "phrase": "C'est pas faux. Les *au·tri·ces, les *au·teurs, les li·brai·res, les mai·sons d'é·di·tion.",
        "consigne": "Écoutez. Sur quelles syllabes entendez-vous un son [z] ? Cliquez sur les 2 syllabes, puis vérifiez.",
        "explication": "« les[z]autrices, les[z]auteurs » : liaison obligatoire devant une voyelle. Devant une consonne (« les libraires », « les maisons »), pas de liaison.",
        "debut": 620.3,
        "fin": 625.9
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue (fin du groupe)"
      ],
      [
        "|",
        "petite pause"
      ],
      [
        "[z]",
        "on ajoute ce son (liaison)"
      ]
    ],
    "modeles": [
      {
        "texte": "C'est <strong>vrai</strong> ↗ | sauf que souvent ces livres ne sont lus qu'une seule <strong>fois</strong> ↘ | avant de prendre la poussière sur une étagère pendant des an<strong>nées</strong>",
        "t": 185,
        "debut": 184.38,
        "fin": 191.6,
        "contour": [
          2,
          2.7,
          2.5,
          1.8,
          1.1,
          0.4,
          -0.3,
          -1,
          -1.7,
          -1.8,
          0.2,
          5.2,
          3.8,
          3.1,
          3.1,
          2,
          0.9,
          -0.2,
          -1.3,
          -2.4,
          -3.5,
          -4.6,
          -2,
          -12,
          5,
          3.7,
          0.9,
          1.4,
          -0.5,
          -3.4,
          3,
          5.7,
          5.2,
          3.6,
          5.2,
          3.9,
          1.9,
          3.3,
          4.8,
          0.1,
          1.5,
          2.4,
          2.4,
          2.3,
          3.2,
          4.2,
          3.9,
          2.8,
          3.4,
          -10,
          -2.8,
          4.3,
          0.5,
          6.5,
          7,
          7.4,
          5.4,
          1.8,
          4.2,
          6.6,
          2.3,
          -4.6,
          -0.6,
          -0.3,
          -0.1,
          0.2,
          0.4,
          0.7,
          0.9,
          1.2,
          1.2,
          -0.7,
          -0.6,
          1.1,
          -0.2,
          0.6,
          -2.7,
          -1.2,
          0.4,
          0.2,
          -0.6,
          -2.5,
          -0.8,
          -1.6,
          -3.4,
          -6.4,
          -1.9,
          -1.8,
          -0.8,
          0.3,
          -0.5,
          0.1,
          -1.3,
          0,
          1.3,
          -1,
          -1,
          -1.5,
          -1.4,
          -3.4,
          -0.3,
          -1.1,
          -1.8,
          0,
          0.1,
          -0.3,
          -0.1,
          0,
          -0.2,
          -1.1,
          -1.2,
          -2,
          -1.4,
          -1.2,
          -4.9,
          -1.2,
          -2.2,
          -1.6,
          -1,
          -1.1
        ],
        "etendue": 11.1
      },
      {
        "texte": "Pas si <strong>vite</strong> | cham<strong>pion</strong>. Une ↗ li<strong>seuse</strong> ↘ | c'est pas du tout dématériali<strong>sé</strong>",
        "t": 236,
        "debut": 235.58,
        "fin": 239.68,
        "contour": [
          4.4,
          3.9,
          2.7,
          1.1,
          1.2,
          1.2,
          1.3,
          1.4,
          0.7,
          -0.3,
          -1.7,
          -1.4,
          0.4,
          0.3,
          -0.2,
          -1.5,
          -1.1,
          -0.7,
          -0.2,
          0.2,
          0.2,
          -0.6,
          -1.1,
          -1.9,
          -1.2,
          -0.5,
          0.2,
          0.4,
          -0.1,
          -0.7,
          -0.7,
          -0.3,
          0.2,
          0.4,
          0.5,
          0.7,
          0.8,
          1,
          1.1,
          2.3,
          3.5,
          4.4,
          4.5,
          4.8,
          4.6,
          4.5,
          4.3,
          4.6,
          4.1,
          2.4,
          1.2,
          2,
          2.8,
          2.8,
          2.5,
          2.3,
          2,
          1.6,
          0.6,
          -0.5,
          -0.9,
          -1.3,
          -2.4,
          -3.3,
          -2.2,
          -1,
          0.1,
          1.2,
          1,
          -2.6,
          -6.3,
          -6.4,
          -6.4,
          -6.4,
          -3.7,
          -1,
          1.7,
          1.2,
          -0.7,
          1.7,
          4.1,
          4,
          3.4,
          -0.5,
          -1.6,
          0,
          -0.7,
          -2.3,
          -2.5,
          -1.6,
          -1.8,
          -1.6,
          -1.4,
          -1.1,
          -0.9,
          -2.2,
          -2.4,
          -2,
          -2.7,
          -3.7,
          -4.3,
          -4.9,
          -5.3,
          -5.9,
          -6,
          -6.2,
          -6.7,
          -8,
          -3.1,
          3.8,
          4.5,
          4.4,
          3.6,
          2.1,
          0.6,
          -0.9,
          -2.5,
          -4,
          -5.5,
          -5.3
        ],
        "etendue": 10.9
      },
      {
        "texte": "Plus nos livres papier passent de main en <strong>main</strong> ↗ | plus le fossé augmente avec la li<strong>seuse</strong> ↗",
        "t": 553,
        "debut": 552.98,
        "fin": 557.92,
        "contour": [
          7.7,
          7.8,
          -1.8,
          -2,
          -2.6,
          2.2,
          6.6,
          6.4,
          6,
          5.7,
          5.1,
          3.6,
          3.6,
          3.7,
          4.1,
          3,
          2.2,
          -10.4,
          -12,
          -0.8,
          -0.9,
          -2.2,
          -4.3,
          0.7,
          0.3,
          -1,
          -1.5,
          -0.8,
          -0.1,
          0.5,
          1.2,
          1,
          -0.6,
          -1.6,
          -0.8,
          -0.1,
          0.7,
          1.5,
          1.4,
          0.9,
          0.4,
          -0.4,
          -1.3,
          -2.1,
          -3,
          -3.9,
          -8.4,
          -10.6,
          -3.6,
          -2.7,
          -2.2,
          -2.6,
          -4,
          -4.8,
          -5.1,
          -5.4,
          -5.7,
          -2.6,
          1.5,
          4.3,
          5.2,
          5.3,
          -1.9,
          -1.7,
          -1.5,
          -1.5,
          -3.9,
          -12,
          -9.9,
          -7.8,
          -5.7,
          -3.6,
          -3.6,
          -3.6,
          6.2,
          5.3,
          4.9,
          2.7,
          0.5,
          -1.6,
          -3.8,
          -6,
          -0.9,
          0.5,
          1.9,
          3.3,
          4.7,
          3.3,
          1.7,
          -0.1,
          -12,
          -9.1,
          -6.3,
          -3.4,
          -2.9,
          -2.2,
          -0.3,
          1.8,
          2,
          2.7,
          3.4,
          -7.8,
          2.6,
          2.7,
          2.7,
          2.4,
          2,
          1.7,
          1.3,
          1,
          -5.6,
          1,
          1.2,
          0.7,
          0.1,
          -0.3,
          -0.7,
          0,
          -0.6,
          -0.8
        ],
        "etendue": 17.9
      },
      {
        "texte": "Qu'un | ou deux[z]ex<strong>pressos</strong> ↘ bien tas<strong>sés</strong>",
        "t": 309,
        "debut": 307.8,
        "fin": 312.9,
        "contour": [
          7.9,
          1.7,
          -1.3,
          -1.6,
          7.5,
          -6.2,
          -7.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -12,
          -12,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.2,
          0.1,
          0.5,
          0.7,
          0.9,
          1.1,
          1.4,
          1.2,
          1.1,
          0.5,
          0,
          -0.2,
          -0.2,
          5.2,
          3,
          0.7,
          -1.5,
          -0.9,
          0.2,
          0.6,
          0.1,
          7.4,
          1.5,
          0.4,
          0.3,
          0.2,
          0.2,
          0.1,
          0,
          -0.1,
          0.1,
          0.2,
          -0.1,
          -0.5,
          -0.8,
          -0.9,
          -1.1,
          -1,
          -0.9,
          -1.2,
          -1.4,
          -1.7,
          -1.6,
          -0.9,
          -0.1,
          0.2,
          0.5,
          0.8,
          0.5,
          -0.1,
          -0.4,
          -0.6,
          -0.9,
          -1.2,
          -1.5,
          -2.3,
          8.9,
          8.3,
          7.8,
          4.5,
          1.2,
          -2.1,
          -5.4,
          -8.7,
          -12,
          1.3
        ],
        "etendue": 15.8
      },
      {
        "texte": "C'est pas <strong>faux</strong> ↘ | Les[z]au<strong>trices</strong> ↗ | les[z]au<strong>teurs</strong> ↗ | les li<strong>braires</strong> ↗ | les maisons d'édi<strong>tion</strong>",
        "t": 621,
        "debut": 620.38,
        "fin": 625.86,
        "contour": [
          1.6,
          3.9,
          5.7,
          6,
          6.2,
          -4.6,
          -5,
          -1,
          -0.5,
          0,
          0.5,
          0.1,
          -1,
          -0.9,
          0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -2.6,
          -2.3,
          -0.6,
          0.3,
          0,
          -2.8,
          -1.5,
          -1.2,
          -1.7,
          -2.9,
          -5.9,
          -4.2,
          -2.4,
          -0.7,
          0.2,
          1,
          2.1,
          2.5,
          2.1,
          1.1,
          0.1,
          -1,
          -2,
          -3,
          -3.2,
          -3,
          -4.9,
          -7,
          -1.8,
          -0.3,
          0.6,
          -2.8,
          -1.8,
          -0.7,
          -1,
          -1.1,
          -0.9,
          -0.4,
          -0.1,
          0.3,
          0.2,
          -1.1,
          -2,
          -1.6,
          -1.3,
          -2.1,
          -1.3,
          -3.1,
          -1.2,
          1.8,
          3.1,
          2.5,
          -2.3,
          -0.5,
          0.2,
          0.4,
          0.2,
          0.2,
          0,
          0.1,
          0.5,
          1,
          1.2,
          0.6,
          -0.1,
          -0.7,
          -1.3,
          -1.9,
          -2.6,
          -3.2,
          -2.9,
          -1.5,
          -1,
          -1.8,
          -1.3,
          0.9,
          3.3,
          4.4,
          2,
          -0.6,
          4.3,
          4.4,
          3.9,
          2.8,
          4.4,
          3.7,
          -8.8,
          -2.3,
          4.2,
          4.2,
          4.1,
          3.9,
          3.8,
          3.6,
          3.2,
          2.1,
          1.8,
          3.7
        ],
        "etendue": 9
      }
    ],
    "etapes": [
      "Écoutez la phrase 2 fois.",
      "Parlez <strong>en même temps</strong> que la voix, 2 fois. Respectez les pauses.",
      "Enregistrez-vous seul·e et comparez les courbes."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "boutonObjection": "Réaction de la collègue (pour le formateur)",
    "essais": [
      {
        "duree": 90,
        "consigne": "Répondez avec vos notes, en suivant les 4 étapes.",
        "ajout": "Pour l'essai 2, ajoutez : « <strong>Pas si vite…</strong> » et « <strong>Si on fait bien les comptes, …</strong> ». Et faites une petite pause avant « sauf que »."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur joue la collègue et réagit. Répondez, puis concédez un point : « <strong>C'est pas faux…</strong> »",
        "ajout": "Pour l'essai 3, terminez par une proposition : « <strong>Il faudrait plutôt…</strong> »."
      },
      {
        "duree": 60,
        "consigne": "Sans vos notes. Seulement l'essentiel : reconnaître, nuancer, proposer.",
        "ajout": ""
      }
    ],
    "objections": [
      "Mais le papier, ce sont des arbres coupés !",
      "Franchement, s'il faut faire des maths pour tout décider…",
      "Tout le monde le fait, pourquoi pas nous ?",
      "Et les tablettes, on les a déjà : c'est gratuit, non ?"
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Répétez les 3 phrases de la mélodie avec la vidéo, en même temps que la voix (5 minutes)."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites les 6 phrases utiles sans regarder (bouton « Vérifier sans regarder »)."
    },
    {
      "jour": "Jour 3",
      "tache": "En réunion, nuancez une fois avec : « C'est vrai, sauf que… »."
    },
    {
      "jour": "Jour 4",
      "tache": "Enregistrez 1 minute : nuancez une idée « évidente » de votre travail, et envoyez-la à votre formateur."
    }
  ],
  "voix": {
    "neuronale": "fr-FR-RemyMultilingualNeural",
    "dossiers": {
      "formateur": "audio/formateur/",
      "neuronale": "audio/neuronal/"
    }
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Choisissez le sujet pendant la discussion libre (champ « Mon sujet » : une idée « évidente » de son entreprise). 1 minute, sans correction."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute la vidéo",
        "role": "Ton ironique et rapide (sketch + voix off). Faites deviner avant chaque écoute. Le passage difficile se réécoute seul."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Trois temps de la nuance : reconnaître (p1, p6), freiner et comparer (p2, p3), argumenter (p4, p5). Faites adapter l'exemple au métier de l'apprenant."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Cible : la pause avant « sauf que » et les liaisons obligatoires. Syllabes à cliquer, puis shadowing."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Vous jouez la collègue. À l'essai 2, lisez une réaction (« Réaction de la collègue »). Retour entre les essais : 2 points au maximum."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même sujet qu'au début. Commentez les 3 chiffres avec l'apprenant."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une réunion réelle, une date."
      }
    ],
    "notes": [
      "Vidéo : sketch d'ARTE (« Écolo mon cul ! ») avec une voix off d'expert, ironique. Registre familier assumé : « c'est pas ouf », « faire péter la facture », « toute une floppée de », « bouquin ». Bon point de discussion : ce qui passe en réunion, et ce qui ne passe pas.",
      "<strong>Minutage</strong> : les 5 phrases de « La mélodie du français » ont été calées sur l'audio (Whisper large-v3-turbo et small, au centième), avec 0,6 s de marge au début, puis retranscrites pour vérifier qu'aucun mot ne manque, même sans les 0,4 premières secondes. Correction par rapport à la v1 : la phrase 1 s'arrêtait sur « étagère » (fin 190,3 → 191,6 s) et l'exercice « expressos » perdait « Qu'un » (début 309,3 → 307,8 s). Les autres extraits (écoute, 6 phrases utiles) restent calés sur la transcription YouTube : écoutez-les avant d'envoyer le lien.",
      "Mélodie : comme dans Accélération v9, chaque phrase de la partie 4 (les 3 modèles et les 2 phrases de l'exercice des liaisons) a sa courbe mesurée ; l'apprenant s'enregistre et voit sa courbe sur celle de la vidéo. Flèches placées uniquement là où la mesure est nette : « C'est vrai » ↗ (+7 demi-tons), « une seule fois » ↘ (−7), « Une ↗ liseuse ↘ » (+3 puis −4,5), « de main en main » ↗ (+9), « la liseuse » ↗ (+7, la phrase continue), « expressos » ↘ (−5), l'énumération « les autrices, les auteurs, les libraires » ↗ (+4 à +5,5 à chaque élément), « C'est pas faux » ↘. Pas de flèche sur « années », « tassés » ni « dématérialisé » : mesure ambiguë. Étendue de la mélodie : 11,1 / 10,9 / 17,9 / 15,8 / 9,0 demi-tons.",
      "La transcription automatique de YouTube se trompe souvent. Il faut lire : écoanxiété (« écanxiété »), arbres (« arres »), pin (« pain »), haches (« Hes »), tronc (« tron »), paquebots (« Pqubo »), pilonnés (« pyonnés »), étain (« éteint »), encre (« ancre »), la liseuse (« l'Éliseuse »), fatras (« fatra »), Proust (« Prou »), une seule liseuse (« une salle liseuse »), coloc (« colloque »), format poche (« Forme à poche »), encrage (« ancrage »), « Avec ou sans liseuse » (« ou sans liseuse »).",
      "Écarts avec le support Drive : « tomber dans le panneau », « se voiler la face », « le nerf de la guerre », « jouer sur les deux tableaux », « sur le papier » et « un sacré chantier » <strong>ne sont pas dits dans la vidéo</strong> (ce sont des tournures des réponses modèles). La vidéo dit « un <strong>beau</strong> chantier de société » et « le <strong>fatras</strong> du numérique » (et non « foutoir »). Les tournures réellement dites sont celles des 6 phrases utiles, plus « la bonne blague », « prendre la poussière », « au pilon », « c'est pas ouf », « à la pelle », « bien vu », « passer de main en main », « prendre du recul ».",
      "Pour la discussion libre (avant le cours), questions du support Drive : papier ou numérique au quotidien ? Votre intuition : livre ou liseuse, lequel est le plus écologique ? Le « zéro papier » en entreprise est-il toujours justifié ?"
    ]
  }
};
