/* Atelier original : prolongement oral du manuel Défi actuel 2, pages 51–57. */
window.IMPACT60 = {
  "meta": {
    "id": "alimentation-futur-a2-bis-v4",
    "lien": "https://orionside.github.io/Atelier_Formation_Francais/Atelier_Alimentation_Futur_A2_bis_v4/",
    "titre": "Alimentation du futur · bis",
    "niveau": "A2+",
    "duree": 45,
    "support": {
      "le": "la vidéo",
      "du": "de la vidéo",
      "dans": "dans la vidéo",
      "Le": "La vidéo"
    },
    "titreSeance": "À table : mes habitudes et mes choix",
    "objectif": "Aujourd'hui, vous apprenez à <strong>dire ce qui change</strong> dans votre alimentation et à <strong>expliquer votre choix</strong>. En une minute, comme à table avec un collègue.",
    "video": {
      "url": "https://youtu.be/e4pOuOy6lpE",
      "titre": "C'est quoi l'alimentation du futur ? (1 jour, 1 question)",
      "duree": "1 min 42"
    },
    "plusLoin": [
      {
        "label": "Regarder la vidéo en entier (1 min 42)",
        "url": "https://youtu.be/e4pOuOy6lpE"
      }
    ]
  },
  "sujet": {
    "lieu": "À la cantine, à midi",
    "qui": "Un collègue français",
    "dit": "« Moi, je mange de moins en moins de viande. Et vous, qu'est-ce qui change dans votre assiette ? »",
    "vous": "Vous répondez : ce que vous mangez, ce qui change, et pourquoi. Puis vous posez une question à votre collègue.",
    "consigne": "Parlez de vos habitudes à table, et de ce qui change.",
    "perso": {
      "question": "De quelle autre habitude voulez-vous parler ?",
      "exemple": "ex. : le sport, les transports, le télétravail",
      "phrase": "Votre collègue vous demande : « Et vous, qu'est-ce qui change ? » Parlez de : {x}. Dites votre habitude, ce qui change, et pourquoi c'est bien."
    },
    "plan": [
      {
        "titre": "Mon habitude",
        "aide": "Des légumes ? J'en mange souvent."
      },
      {
        "titre": "Ce qui change",
        "aide": "Je mange de plus en plus de… et de moins en moins de…"
      },
      {
        "titre": "Pourquoi je fais ce choix",
        "aide": "Ça permet de moins jeter."
      },
      {
        "titre": "Ma question",
        "aide": "Et vous, vous avez déjà essayé ?"
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "Je ne savais pas comment commencer",
    "Je ne savais pas dire « de plus en plus »",
    "Je n'étais pas sûre de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "Demain, dans nos assiettes",
      "debut": 12.16,
      "fin": 57.81,
      "pourquoi": "La voix explique ce qui va changer dans notre assiette, et pourquoi. Vous allez faire la même chose avec vos habitudes.",
      "devine": "À votre avis, qu'est-ce qu'on va manger dans 20 ans ? Répondez à voix haute : 2 idées.",
      "questions": [
        {
          "q": "Dans la vidéo, quel problème est associé à la viande et au maïs ?",
          "options": [
            "Ils coûtent trop cher.",
            "Ils demandent beaucoup d'eau.",
            "Ils n'ont pas de goût."
          ],
          "bonne": 1,
          "explication": "La voix dit : « des produits qui, comme la viande ou le maïs, <strong>nécessitent beaucoup d'eau</strong> ». Nécessiter, c'est avoir besoin de quelque chose."
        },
        {
          "q": "Où peut-on trouver des protéines, sans manger de viande ?",
          "options": [
            "Dans le chocolat et la farine.",
            "Dans l'eau.",
            "Dans des plantes comme le soja, et dans les insectes."
          ],
          "bonne": 2,
          "explication": "« On peut en trouver ailleurs, <strong>dans des plantes comme le soja, mais aussi dans les insectes</strong>. » Ailleurs, c'est dans un autre endroit."
        }
      ],
      "trous": [
        {
          "avant": "D'ici une vingtaine d'années, le contenu de nos assiettes va beaucoup",
          "apres": ".",
          "aide": "être différent.",
          "reponses": [
            "changer"
          ],
          "solution": "changer"
        },
        {
          "avant": "Manger des grillons au chocolat va devenir de plus en",
          "apres": "banal.",
          "aide": "ça augmente.",
          "reponses": [
            "plus"
          ],
          "solution": "plus"
        }
      ],
      "difficile": {
        "debut": 24.66,
        "fin": 30.09,
        "texte": "Passage facultatif. La vidéo évoque la population mondiale en 2030. Écoutez les nombres si vous le souhaitez. Nourrir, c'est donner à manger. Vous n'avez pas besoin de retenir ces nombres pour parler de vos habitudes."
      }
    },
    {
      "id": "B",
      "titre": "Moins d'eau, zéro déchet",
      "debut": 57.44,
      "fin": 96.7,
      "pourquoi": "La voix donne trois nouveautés. Pour chacune, elle dit pourquoi c'est bien… ou ce qui manque encore. C'est utile pour donner votre avis.",
      "devine": "Chez vous, qu'est-ce que vous faites avec les restes ? Les restes, c'est la nourriture non mangée. Répondez à voix haute.",
      "questions": [
        {
          "q": "Selon cette vidéo, le steak de laboratoire a-t-il le goût de la vraie viande ?",
          "options": [
            "Oui, exactement le même goût.",
            "Non, pas encore.",
            "La vidéo ne le dit pas."
          ],
          "bonne": 1,
          "explication": "« Ce steak synthétique <strong>n'a pas encore la saveur de l'original</strong>. » La saveur, c'est le goût. Synthétique : fabriqué, pas naturel."
        },
        {
          "q": "« Zéro déchet » : qu'est-ce que ça veut dire dans la vidéo ?",
          "options": [
            "On ne jette plus de nourriture : on cuisine les restes.",
            "On mange seulement des algues.",
            "On ne va plus au restaurant."
          ],
          "bonne": 0,
          "explication": "« Savoir inventer de nouvelles recettes pour <strong>récupérer les restes</strong>, c'est ça aussi la cuisine du futur. » Un déchet, c'est une chose qu'on jette à la poubelle."
        }
      ],
      "trous": [
        {
          "avant": "Cette nouvelle technologie",
          "apres": "d'économiser beaucoup d'eau.",
          "aide": "rend possible.",
          "reponses": [
            "permet"
          ],
          "solution": "permet"
        },
        {
          "avant": "Un tiers de la production alimentaire mondiale est",
          "apres": "et perdue.",
          "aide": "jetée, non utilisée.",
          "reponses": [
            "gaspillee",
            "gaspille"
          ],
          "solution": "gaspillée"
        }
      ],
      "difficile": {
        "debut": 73.02,
        "fin": 78.22,
        "texte": "Passage facultatif. La laitue est une salade verte. La nori et le wakamé sont des algues utilisées en cuisine. Pour votre réponse, vous pouvez garder un aliment que vous connaissez."
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour annoncer un changement à venir. Cette phrase est un prolongement : l'objectif principal reste de parler de vos habitudes.",
      "forme": "… va beaucoup changer.",
      "film": {
        "texte": "D'ici une vingtaine d'années, le contenu de nos assiettes <strong>va beaucoup changer</strong>.",
        "t": 13,
        "debut": 12.03,
        "fin": 18.29,
        "contour": [
          -9.8,
          -9.4,
          -2.6,
          -2.5,
          1.2,
          4.8,
          5.1,
          6.4,
          7.6,
          8.9,
          8.0,
          6.1,
          0.8,
          -3.6,
          -5.3,
          -7.7,
          -8.1,
          -7.6,
          -3.1,
          1.3,
          5.8,
          6.5,
          5.0,
          1.9,
          5.5,
          4.4,
          2.3,
          0.7,
          -2.1,
          -0.7,
          -1.3,
          -1.0,
          -0.9,
          0.0,
          2.2,
          3.4,
          1.3,
          -0.8,
          -2.9,
          -5.0,
          -7.1,
          -9.2,
          -8.9,
          -4.9,
          -0.8,
          -1.7,
          -2.7,
          -3.4,
          -3.5,
          -0.2,
          3.1,
          6.4,
          6.9,
          7.2,
          6.7,
          6.1,
          11.1,
          7.4,
          3.5,
          3.0,
          1.7,
          -3.5,
          -4.0,
          -5.4,
          -3.7,
          1.8,
          4.6,
          5.2,
          3.0,
          0.8,
          -0.5,
          -1.3,
          -0.2,
          0.9,
          2.0,
          1.7,
          2.8,
          3.6,
          2.3,
          1.0,
          -0.2,
          -1.5,
          -2.8,
          -4.1,
          -5.3,
          -5.2,
          -5.3,
          -5.5,
          -5.6,
          -5.6,
          -5.6,
          -5.6,
          -2.7,
          2.4,
          4.2,
          5.7,
          5.6,
          3.9,
          1.4,
          4.1,
          6.7,
          7.1,
          6.8,
          4.6,
          -0.9,
          -3.3,
          -6.2,
          -9.1,
          -12.0,
          -12.0,
          -3.6,
          -5.0,
          -6.4,
          -7.1,
          -8.4,
          -9.3,
          -10.2,
          -11.1,
          -12.0,
          -12.0
        ],
        "etendue": 16.9
      },
      "exemple": "Mon alimentation va beaucoup changer : je vais cuisiner davantage.",
      "detect": [
        "va beaucoup changer",
        "va changer"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour dire que quelque chose augmente. Le contraire : de moins en moins.",
      "forme": "… de plus en plus… / … de moins en moins…",
      "film": {
        "texte": "En Europe, manger des grillons au chocolat ou des vers de farine va devenir <strong>de plus en plus</strong> banal.",
        "t": 51,
        "debut": 50.08,
        "fin": 56.48,
        "contour": [
          -11.0,
          -10.4,
          -10.1,
          -7.7,
          -5.2,
          -2.8,
          -2.2,
          -1.4,
          -1.4,
          1.1,
          2.2,
          3.1,
          2.2,
          1.3,
          0.4,
          -0.4,
          -1.3,
          -2.2,
          -2.1,
          -0.7,
          1.2,
          1.8,
          0.6,
          1.6,
          2.0,
          -0.2,
          -1.4,
          -3.9,
          -5.9,
          -6.1,
          -4.3,
          -2.6,
          -0.8,
          0.9,
          3.0,
          3.3,
          1.5,
          -1.9,
          -4.5,
          -5.6,
          -1.5,
          2.5,
          2.0,
          0.3,
          1.9,
          1.6,
          1.2,
          0.3,
          -0.5,
          -1.4,
          -5.7,
          -5.4,
          -5.9,
          -7.0,
          -7.0,
          -7.5,
          -4.0,
          -4.5,
          -4.2,
          -4.5,
          -0.5,
          3.6,
          3.0,
          -2.5,
          -5.2,
          -3.6,
          -2.0,
          -0.3,
          1.3,
          2.9,
          3.9,
          4.9,
          1.8,
          -4.9,
          -7.3,
          -8.2,
          -9.1,
          -9.9,
          -10.8,
          -10.7,
          -10.3,
          -4.4,
          -4.0,
          -0.2,
          0.0,
          6.2,
          11.6,
          0.6,
          2.3,
          3.4,
          4.9,
          5.9,
          5.8,
          0.8,
          0.8,
          0.3,
          2.9,
          5.6,
          5.7,
          12.0,
          12.0,
          10.6,
          9.2,
          8.1,
          7.8,
          7.6,
          7.2,
          5.0,
          5.8,
          3.4,
          1.4,
          -4.9,
          -7.2,
          -8.9,
          -9.8,
          -10.1,
          -10.3,
          -10.6,
          -10.8,
          -10.1
        ],
        "etendue": 18.3
      },
      "exemple": "Je mange de plus en plus de légumes et de moins en moins de viande.",
      "detect": [
        "de plus en plus",
        "de moins en moins"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour parler d'une habitude : ce qu'on fait souvent.",
      "forme": "J'ai l'habitude de…",
      "film": {
        "texte": "Les Africains et les Asiatiques <strong>ont</strong> depuis longtemps <strong>l'habitude de</strong> manger des chenilles, des termites ou des sauterelles.",
        "t": 44,
        "debut": 43.8,
        "fin": 50.5,
        "contour": [
          2.5,
          2.5,
          1.6,
          1.0,
          0.3,
          -0.3,
          -1.0,
          -1.6,
          -0.4,
          0.4,
          -1.3,
          1.8,
          0.7,
          -6.7,
          -8.3,
          1.6,
          0.5,
          -1.2,
          0.4,
          2.0,
          1.7,
          1.3,
          0.4,
          -2.8,
          -5.0,
          -5.5,
          -4.9,
          -3.1,
          -2.9,
          -3.7,
          -1.5,
          -2.8,
          -1.2,
          0.5,
          2.1,
          3.7,
          5.4,
          7.0,
          -2.1,
          -1.3,
          -0.6,
          0.2,
          0.1,
          -5.8,
          -0.1,
          0.0,
          -3.7,
          -7.5,
          -11.2,
          -5.7,
          1.8,
          5.1,
          -5.0,
          -11.1,
          0.5,
          12.0,
          9.2,
          5.4,
          8.9,
          -1.4,
          -1.1,
          0.2,
          -0.1,
          1.8,
          3.7,
          2.9,
          -0.6,
          -0.8,
          -1.0,
          -1.4,
          -0.8,
          -0.4,
          -7.8,
          -12.0,
          1.6,
          0.7,
          -1.0,
          -2.7,
          -2.9,
          -1.0,
          0.8,
          0.8,
          1.5,
          2.7,
          2.7,
          0.8,
          -2.2,
          -3.5,
          -2.7,
          -1.9,
          -0.2,
          0.5,
          1.3,
          2.0,
          0.3,
          1.4,
          3.0,
          4.2,
          4.8,
          4.1,
          2.1,
          0.1,
          -1.9,
          -1.8,
          -1.9,
          -2.4,
          -3.6,
          -4.5,
          -3.0,
          -1.4,
          -1.5,
          -0.2,
          1.1,
          0.8,
          -0.7,
          0.2,
          1.2,
          1.3,
          -0.4,
          -3.1
        ],
        "etendue": 11.7
      },
      "exemple": "J'ai l'habitude de préparer une soupe avec les restes.",
      "detect": [
        "l habitude de",
        "l habitude d"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour éviter de répéter « des légumes » : j'en mange. Avec deux verbes : je peux en préparer.",
      "forme": "On peut en trouver… / J'en mange…",
      "film": {
        "texte": "Or, <strong>on peut en trouver</strong> ailleurs, dans des plantes comme le soja, mais aussi dans les insectes.",
        "t": 39,
        "debut": 38.26,
        "fin": 44.63,
        "contour": [
          2.4,
          6.6,
          8.2,
          8.4,
          6.9,
          -0.3,
          -7.6,
          -10.7,
          -10.9,
          1.7,
          1.9,
          2.2,
          1.5,
          5.8,
          10.1,
          7.8,
          5.3,
          3.0,
          3.5,
          4.1,
          4.2,
          2.6,
          2.2,
          1.2,
          -1.7,
          -2.9,
          -2.4,
          -2.2,
          2.7,
          -1.8,
          -3.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -6.3,
          -7.0,
          -5.3,
          -5.8,
          -4.4,
          -3.0,
          -2.5,
          -2.1,
          -1.6,
          -1.8,
          -2.6,
          -3.5,
          -4.3,
          -5.2,
          -6.0,
          -3.8,
          -3.7,
          -3.7,
          -3.5,
          3.0,
          2.8,
          2.0,
          2.1,
          2.0,
          -0.8,
          -5.5,
          -7.1,
          -8.8,
          -10.4,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          2.2,
          2.9,
          3.9,
          4.5,
          4.1,
          5.4,
          6.8,
          6.4,
          2.2,
          -2.0,
          -6.1,
          -10.3,
          -10.0,
          -9.7,
          -4.4,
          -6.0,
          -6.2,
          -3.4,
          -2.7,
          0.8,
          3.5,
          5.7,
          3.4,
          0.7,
          -3.7,
          -4.2,
          -5.6,
          -5.5,
          -2.2,
          1.1,
          0.4,
          -0.4,
          -0.5,
          -0.6,
          -0.6,
          -0.7,
          -0.4,
          -0.3,
          -4.2,
          -8.0,
          -11.9,
          -0.7,
          0.3,
          0.4,
          0.5,
          0.4,
          0.0
        ],
        "etendue": 18.2
      },
      "exemple": "Des légumes ? J'en mange tous les jours. Du riz ? Je peux en préparer.",
      "detect": [
        "j en mange",
        "j en bois",
        "on peut en"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour expliquer pourquoi c'est bien.",
      "forme": "Ça permet de…",
      "film": {
        "texte": "Cette nouvelle technologie <strong>permet d'économiser</strong> beaucoup d'eau…",
        "t": 64,
        "debut": 63.62,
        "fin": 67.56,
        "contour": [
          -0.5,
          -1.1,
          -1.8,
          -2.5,
          -3.3,
          -4.0,
          -4.7,
          -5.5,
          -6.2,
          -6.0,
          -4.9,
          -2.6,
          0.5,
          2.3,
          2.5,
          2.5,
          2.4,
          1.8,
          0.2,
          -1.4,
          -3.0,
          -3.2,
          -1.7,
          -0.1,
          1.4,
          1.5,
          1.1,
          -0.6,
          -0.4,
          -0.2,
          0.0,
          -0.3,
          -1.2,
          -1.8,
          -2.1,
          -2.1,
          -2.1,
          -2.5,
          -2.8,
          -1.0,
          0.9,
          2.7,
          2.8,
          2.2,
          1.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.7,
          -4.9,
          -4.2,
          -3.8,
          -3.8,
          -5.7,
          -5.7,
          1.0,
          1.9,
          2.4,
          1.7,
          -0.6,
          -0.8,
          2.1,
          2.0,
          1.3,
          0.6,
          1.1,
          1.0,
          0.4,
          0.3,
          0.5,
          0.5,
          -0.2,
          -1.3,
          -2.2,
          1.1,
          1.1,
          0.9,
          -1.2,
          -4.2,
          -4.4,
          -3.0,
          -1.8,
          4.0,
          4.2,
          4.0,
          3.8,
          3.5,
          3.3,
          3.3,
          2.9,
          2.7,
          2.7,
          2.0,
          0.8,
          -0.3,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.6,
          -5.4,
          -5.1
        ],
        "etendue": 8.8
      },
      "exemple": "Cuisiner les restes, ça permet de moins jeter.",
      "detect": [
        "permet de",
        "permet d"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour inviter l'autre à répondre. Choisissez « tu » ou « vous » selon votre relation avec cette personne.",
      "forme": "Tu as déjà essayé ? / Vous avez déjà essayé ?",
      "film": {
        "texte": "<strong>Tu as déjà essayé ?</strong>",
        "t": 56,
        "debut": 55.8,
        "fin": 57.94,
        "contour": [
          -10.1,
          -10.1,
          -10.0,
          -9.9,
          -9.9,
          -9.5,
          -9.4,
          -9.2,
          -9.2,
          -9.2,
          -9.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          7.2,
          6.5,
          5.8,
          5.8,
          5.1,
          4.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          3.5,
          3.4,
          3.3,
          3.3,
          3.3,
          1.8,
          0.3,
          -1.2,
          -1.3,
          -1.5,
          -1.9,
          -2.3,
          -2.3,
          -2.3,
          -2.0,
          -2.0,
          0.0,
          1.2,
          1.5,
          1.5,
          1.5,
          1.2,
          1.0,
          0.9,
          0.8,
          0.0,
          -0.7,
          -1.5,
          -2.3,
          -1.6,
          -0.9,
          -0.1,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          -0.1,
          -0.9,
          -1.0,
          -1.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.1,
          -0.3,
          -0.5,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0
        ],
        "etendue": 25.5
      },
      "exemple": "Je prépare une salade avec des légumes grillés. Vous avez déjà essayé ?",
      "detect": [
        "deja essaye",
        "vous avez deja",
        "tu as deja"
      ]
    }
  ],
  "prononciation": {
    "intro": "Dans ces extraits, écoutez comment la voix <strong>monte</strong> sur un mot important et <strong>descend</strong> à certaines fins de phrase. Reprenez un exemple à la fois.",
    "regle": [
      "Dans le premier exemple, la voix monte sur « beaucoup », puis descend sur « changer ».",
      "Dans le deuxième exemple, écoutez le premier « plus », puis la fin du mot « banal ».",
      "Ces mouvements appartiennent aux exemples de la vidéo. Une question peut aussi se terminer avec une voix qui descend."
    ],
    "attention": "Les flèches décrivent la voix humaine de la vidéo. Votre voix peut être différente et rester claire. Les courbes servent à comparer les essais ; elles ne donnent pas une note de niveau.",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "… va de·ve·nir de *plus en plus ba·nal.",
        "consigne": "Écoutez la fin de la phrase. Sur quelle syllabe la voix monte-t-elle le plus haut ? Cliquez sur une syllabe, puis vérifiez.",
        "explication": "La voix monte sur le premier « plus » : c'est le mot important. Sur « banal », elle descend : la phrase est finie.",
        "debut": 53.58,
        "fin": 56.48
      },
      {
        "titre": "Phrase 2",
        "phrase": "… per·met d'é·co·no·mi·ser beau·*coup d'eau.",
        "consigne": "Écoutez. Sur quelle syllabe la voix monte-t-elle ? Cliquez sur une syllabe, puis vérifiez.",
        "explication": "La voix monte sur « -coup » de « beaucoup » : c'est le mot qui dit « combien ».",
        "debut": 64.96,
        "fin": 67.56
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte (mesuré dans la vidéo)"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue"
      ],
      [
        "|",
        "petite pause"
      ],
      [
        "‿",
        "on enchaîne, sans pause"
      ]
    ],
    "modeles": [
      {
        "texte": "Le contenu de nos‿assiettes va beau<strong>coup</strong> ↗ chan<strong>ger</strong> ↘",
        "t": 15,
        "debut": 14.08,
        "fin": 18.28,
        "contour": [
          -9.4,
          -9.4,
          -7.3,
          -5.2,
          -3.1,
          -1.0,
          -1.3,
          -2.4,
          -3.0,
          -3.6,
          -3.6,
          -3.7,
          -1.7,
          0.3,
          2.3,
          4.3,
          6.3,
          6.7,
          7.0,
          7.0,
          6.7,
          6.3,
          6.0,
          11.0,
          12.0,
          4.0,
          3.3,
          3.2,
          2.6,
          2.1,
          -0.1,
          -4.2,
          -4.2,
          -4.4,
          -5.9,
          -5.2,
          -1.8,
          2.2,
          3.9,
          5.0,
          5.0,
          3.6,
          2.1,
          0.7,
          0.0,
          -1.3,
          -1.5,
          -0.9,
          -0.2,
          0.4,
          1.1,
          1.7,
          1.5,
          1.8,
          3.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.9,
          -5.3,
          -5.5,
          -5.4,
          -5.5,
          -5.5,
          -5.6,
          -5.6,
          -5.7,
          -5.9,
          -5.9,
          -5.8,
          -5.8,
          -5.5,
          -2.1,
          1.6,
          3.0,
          3.9,
          5.4,
          5.5,
          5.4,
          5.1,
          2.2,
          1.4,
          3.1,
          4.8,
          6.5,
          6.7,
          7.0,
          6.6,
          5.5,
          2.9,
          -1.1,
          -3.3,
          -4.8,
          -6.2,
          -7.6,
          -9.1,
          -10.6,
          -12.0,
          -9.0,
          -8.3,
          -7.7,
          -7.1,
          -6.4,
          -7.0,
          -8.1,
          -8.6,
          -8.9,
          -9.7,
          -10.4,
          -11.2,
          -12.0,
          -12.0,
          -12.0,
          -12.0
        ],
        "etendue": 21.6
      },
      {
        "texte": "… va devenir de <strong>plus</strong> ↗ en plus ba<strong>nal</strong> ↘",
        "t": 54,
        "debut": 53.58,
        "fin": 56.48,
        "contour": [
          3.0,
          3.2,
          3.3,
          2.8,
          1.2,
          -1.3,
          -4.9,
          -7.6,
          -8.9,
          -9.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -11.9,
          -9.1,
          -6.2,
          -6.2,
          -6.1,
          -5.4,
          -2.6,
          -1.6,
          -1.8,
          -1.9,
          -1.0,
          -0.1,
          0.8,
          10.4,
          12.0,
          0.4,
          -1.2,
          -1.7,
          -1.2,
          0.2,
          1.1,
          1.5,
          1.5,
          1.9,
          2.9,
          3.7,
          4.1,
          4.0,
          4.0,
          2.8,
          1.5,
          0.2,
          -1.0,
          -1.0,
          -1.0,
          -1.4,
          -0.4,
          0.6,
          1.7,
          2.7,
          3.7,
          3.7,
          3.8,
          3.8,
          7.9,
          12.0,
          11.9,
          11.0,
          10.2,
          9.6,
          9.0,
          8.4,
          7.8,
          7.4,
          6.5,
          6.1,
          6.0,
          6.0,
          5.9,
          5.8,
          5.8,
          5.7,
          5.7,
          5.5,
          4.0,
          3.0,
          3.5,
          4.0,
          3.9,
          3.7,
          1.8,
          0.5,
          -0.5,
          -3.2,
          -6.0,
          -6.8,
          -8.2,
          -8.7,
          -9.7,
          -10.1,
          -11.2,
          -11.4,
          -11.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -11.9
        ],
        "etendue": 23.5
      },
      {
        "texte": "Cette nouvelle technologie permet d'économiser beau<strong>coup</strong> ↗ d'eau…",
        "t": 64,
        "debut": 63.62,
        "fin": 67.56,
        "contour": [
          -0.5,
          -1.1,
          -1.8,
          -2.5,
          -3.3,
          -4.0,
          -4.7,
          -5.5,
          -6.2,
          -6.0,
          -4.9,
          -2.6,
          0.5,
          2.3,
          2.5,
          2.5,
          2.4,
          1.8,
          0.2,
          -1.4,
          -3.0,
          -3.2,
          -1.7,
          -0.1,
          1.4,
          1.5,
          1.1,
          -0.6,
          -0.4,
          -0.2,
          0.0,
          -0.3,
          -1.2,
          -1.8,
          -2.1,
          -2.1,
          -2.1,
          -2.5,
          -2.8,
          -1.0,
          0.9,
          2.7,
          2.8,
          2.2,
          1.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.7,
          -4.9,
          -4.2,
          -3.8,
          -3.8,
          -5.7,
          -5.7,
          1.0,
          1.9,
          2.4,
          1.7,
          -0.6,
          -0.8,
          2.1,
          2.0,
          1.3,
          0.6,
          1.1,
          1.0,
          0.4,
          0.3,
          0.5,
          0.5,
          -0.2,
          -1.3,
          -2.2,
          1.1,
          1.1,
          0.9,
          -1.2,
          -4.2,
          -4.4,
          -3.0,
          -1.8,
          4.0,
          4.2,
          4.0,
          3.8,
          3.5,
          3.3,
          3.3,
          2.9,
          2.7,
          2.7,
          2.0,
          0.8,
          -0.3,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.6,
          -5.4,
          -5.1
        ],
        "etendue": 8.8
      },
      {
        "texte": "Tu as déjà essa<strong>yé</strong> ↘ ?",
        "t": 56,
        "debut": 55.8,
        "fin": 57.94,
        "contour": [
          -10.1,
          -10.1,
          -10.0,
          -9.9,
          -9.9,
          -9.5,
          -9.4,
          -9.2,
          -9.2,
          -9.2,
          -9.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          7.2,
          6.5,
          5.8,
          5.8,
          5.1,
          4.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          3.5,
          3.4,
          3.3,
          3.3,
          3.3,
          1.8,
          0.3,
          -1.2,
          -1.3,
          -1.5,
          -1.9,
          -2.3,
          -2.3,
          -2.3,
          -2.0,
          -2.0,
          0.0,
          1.2,
          1.5,
          1.5,
          1.5,
          1.2,
          1.0,
          0.9,
          0.8,
          0.0,
          -0.7,
          -1.5,
          -2.3,
          -1.6,
          -0.9,
          -0.1,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          -0.1,
          -0.9,
          -1.0,
          -1.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.1,
          -0.3,
          -0.5,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0
        ],
        "etendue": 25.5
      }
    ],
    "etapes": [
      "Écoutez une phrase deux fois.",
      "Répétez avec la voix deux fois. Faites une pause si nécessaire.",
      "Enregistrez-vous seule. Écoutez si les mots sont clairs ; la courbe est facultative."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "boutonObjection": "Question du collègue (pour le formateur)",
    "essais": [
      {
        "duree": 90,
        "consigne": "Parlez avec vos notes : votre habitude, ce qui change, pourquoi, puis votre question.",
        "ajout": "Pour l'essai 2, ajoutez une expression : « de plus en plus » ou « de moins en moins »."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur joue le collègue et vous pose une question. Répondez.",
        "ajout": "Pour l'essai 3, ajoutez « Ça permet de… », puis une question : « Et vous, vous avez déjà essayé ? »"
      },
      {
        "duree": 60,
        "consigne": "Gardez l'essentiel. Utilisez encore vos mots-clés si vous en avez besoin.",
        "ajout": ""
      }
    ],
    "objections": [
      "Et les légumes, vous en mangez souvent ?",
      "Entre la soupe et la salade, laquelle préférez-vous ?",
      "Comment préparez-vous votre plat préféré ?",
      "Et les restes, qu'est-ce que vous en faites ?"
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Choisissez une phrase de la vidéo. Écoutez-la, puis répétez-la deux fois."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites trois phrases utiles avec vos propres habitudes, sans regarder si possible."
    },
    {
      "jour": "Jour 3",
      "tache": "Présentez un plat : son nom, ses ingrédients, sa préparation. Puis dites si vous en mangez souvent."
    },
    {
      "jour": "Jour 4",
      "tache": "Parlez une minute de vos habitudes et de ce qui change. Réécoutez-vous, puis choisissez une phrase à réutiliser."
    }
  ],
  "voix": {
    "moteur": "Qwen3-TTS-12Hz-1.7B-Base-8bit",
    "dossier": "audio/qwen3-tts/"
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Jouez le collègue : « Moi, je mange de moins en moins de viande. Et vous, qu'est-ce qui change dans votre assiette ? » 1 minute, sans correction. Pour un A2+, 5 à 7 phrases, c'est déjà bien."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute la vidéo",
        "role": "Deux extraits de la vidéo, avec images et deux questions chacun. Faites écouter une première fois pour l'idée générale, puis pour la réponse. Les passages difficiles sont facultatifs. Les nombres et les noms d'insectes ne sont pas des objectifs de production."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Travaillez trois phrases en priorité : la progression, le pronom en et la raison du choix. Les autres phrases sont proposées pour le réemploi. Si ces acquis sont solides, choisissez une seule activité du manuel dans le panneau replié."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Prenez un ou deux modèles de la vidéo. Écoute, répétition, puis intelligibilité. Les contours décrivent ces extraits : ils ne fixent aucune intonation obligatoire du français. La capsule du manuel porte sur la lettre g, proposée en activité facultative."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Le même message, trois essais. La durée est un cadre, pas une épreuve de vitesse. Autorisez les mots-clés et gardez la même durée si la réduction déstabilise l'apprenante. Un retour concret entre les essais suffit."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même situation. Comparez surtout les idées exprimées, les expressions réutilisées et la facilité de compréhension. Les chiffres automatiques sont des indications approximatives et ne valent pas une évaluation CECRL."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une situation réelle (un déjeuner, une pause-café), une date."
      }
    ],
    "notes": [
      "Analyse du manuel Défi actuel 2, unité trois, pages cinquante et un à cinquante-sept : spécialités des outre-mer, cuisine camerounaise, ingrédients et préparation, avis sur un plat, pronom en, progression et choix avec les pronoms interrogatifs. Les activités proposées ici sont originales et prolongent ces objectifs.",
      "Les pistes trente-cinq à trente-neuf ont été examinées avec leurs transcriptions officielles et les durées du lecteur. La piste trente-cinq fait décrire et qualifier des plats ; trente-six porte sur une commande au restaurant ; trente-sept sur les habitudes avec en ; trente-huit sur les tendances et les choix ; trente-neuf distingue une progression d'une simple comparaison. Les fichiers sonores du manuel ne sont pas copiés dans cet atelier.",
      "Pour limiter la charge cognitive, gardez la situation de cantine pendant toute la séance. Priorités : une habitude avec en, un changement et une raison simple. Un plat familier suffit. Réservez les quatre formes interrogatives et la lettre g à une seule activité de réemploi, selon les besoins.",
      "La vidéo est un ancien document de vulgarisation, avec un vocabulaire parfois plus difficile que celui du manuel. Elle sert à repérer des expressions ; ses prévisions ne sont pas présentées comme des faits actuels. Toute la vidéo n'est pas à comprendre ni à mémoriser.",
      "Les consignes, expressions, exemples, compléments et notes ont une lecture féminine de synthèse. La voix vient d'un enregistrement de synthèse fourni par le formateur. Les lectures sont découpées en groupes de mots courts, avec une pause aux virgules et aux points. Une transcription automatique contrôle les mots, mais ne garantit pas l'accent ou le naturel.",
      "Les courbes existantes se rapportent uniquement à la voix humaine de la vidéo. Une lecture Qwen peut avoir une autre mélodie. Ne demandez pas de reproduire exactement une courbe ; écoutez d'abord l'intelligibilité et le regroupement des mots.",
      "Le CECRL décrit des capacités de communication, pas une liste de points de grammaire française. Pour ce public A2 renforcé, visez une description courte et une interaction simple sur l'alimentation. La compréhension dépend de la clarté, de la familiarité du sujet et de la possibilité de répéter. L'atelier ne certifie pas le niveau de l'apprenante."
    ]
  },
  "manuel": {
    "titre": "Réutiliser le manuel, si nécessaire",
    "intro": "Choisissez une seule activité avec votre formateur. Vous connaissez déjà certaines expressions : utilisez-les avec votre propre plat.",
    "activites": [
      {
        "titre": "Mon plat — pages 52 à 55",
        "consigne": "Présentez un plat de votre choix : les ingrédients, la préparation, puis votre avis.",
        "exemples": [
          "C'est une soupe de mon pays. Il y a des légumes et du riz.",
          "Les légumes sont cuits dans l'eau. Je trouve ça délicieux."
        ]
      },
      {
        "titre": "J’en mange — page 55",
        "consigne": "Votre collègue nomme un aliment. Répondez avec « en », puis indiquez une fréquence.",
        "exemples": [
          "Du poisson ? J'en mange parfois.",
          "De la viande ? Je n'en mange pas.",
          "Des légumes ? Je peux en préparer pour ce soir."
        ]
      },
      {
        "titre": "Lequel ? Laquelle ? — pages 56 et 57",
        "consigne": "Choisissez entre deux plats, puis entre deux boissons. Posez la question à votre collègue.",
        "exemples": [
          "Le riz ou le couscous : lequel préférez-vous ?",
          "La soupe ou la salade : laquelle préférez-vous ?",
          "Parmi ces légumes, lesquels choisissez-vous ?",
          "Parmi ces boissons, lesquelles préférez-vous ?"
        ]
      },
      {
        "titre": "La lettre g — page 57",
        "consigne": "Écoutez deux mots à la fois, puis répétez. Dans « légume » et « grillé », le g se prononce comme dans « gare ». Dans « orange » et « fromage », il se prononce comme dans « jour ».",
        "exemples": [
          "Un légume. Un légume grillé.",
          "Une orange. Du fromage."
        ]
      }
    ]
  }
};
