/* =====================================================================
   SÉANCE IMPACT 60 (format 45 minutes) — FICHIER DE CONTENU
   Atelier : BYD ne prend pas le marché automobile. Elle prend les océans.
   Tout ce qui suit « window.IMPACT60 = » doit rester du JSON strict.
   Mode d'emploi : MODELE_IMPACT60.md
   ===================================================================== */
window.IMPACT60 = {
  "meta": {
    "id": "byd-oceans-b2-v1",
    "titre": "BYD",
    "niveau": "B2",
    "duree": 45,
    "support": {
      "le": "la vidéo",
      "du": "de la vidéo",
      "dans": "dans la vidéo",
      "Le": "La vidéo"
    },
    "titreSeance": "Faire soi-même… ou confier à d'autres ?",
    "objectif": "Aujourd'hui, vous apprenez à <strong>défendre un choix : faire vous-même ou confier à un partenaire</strong>. Vous dites le problème, le risque, votre décision. En 1 minute, sans chercher vos mots.",
    "video": {
      "url": "https://youtu.be/K_fG0ezFXy0",
      "titre": "BYD ne prend pas le marché automobile. Elle prend les océans (ElecTruc)",
      "duree": "18 min"
    },
    "plusLoin": [
      {
        "label": "Regarder la vidéo en entier (18 min)",
        "url": "https://youtu.be/K_fG0ezFXy0"
      }
    ]
  },
  "sujet": {
    "lieu": "Réunion de direction",
    "qui": "Le directeur financier",
    "dit": "« Notre prestataire augmente ses prix de 40 %. Et si nous faisions ce travail nous-mêmes ? »",
    "vous": "Vous voyez l'intérêt. Mais vous voyez aussi un risque : cela coûte cher, et c'est pour longtemps.",
    "consigne": "Donnez votre avis.",
    "perso": {
      "question": "Dans votre entreprise, qu'est-ce qu'on pourrait faire soi-même au lieu de le confier à un prestataire ?",
      "exemple": "ex. : la traduction, la formation, l'informatique, le transport",
      "phrase": "En réunion, quelqu'un propose de faire nous-mêmes, au lieu de le confier à un prestataire : {x}. Vous voyez l'intérêt, mais aussi un risque."
    },
    "plan": [
      {
        "titre": "La situation",
        "aide": "Pendant des années, la règle était simple : …"
      },
      {
        "titre": "Le plus grave",
        "aide": "… n'est pas le pire. Le pire, c'est…"
      },
      {
        "titre": "Le risque",
        "aide": "Reste le vrai contre-argument : …"
      },
      {
        "titre": "Ma décision",
        "aide": "Retirez toutes les nuances, et voici ce qui reste : …"
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "Je ne savais pas comment commencer",
    "Je ne savais pas comment relier mes idées",
    "Je n'étais pas sûr·e de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "Neuf fois plus cher !",
      "debut": 73.52,
      "fin": 109.53,
      "pourquoi": "Un prestataire devient très cher : c'est le point de départ de votre sujet du jour.",
      "devine": "Louer un bateau pour transporter des voitures : en 2021, cela coûte environ <strong>12 500 dollars par jour</strong>. Et en 2024, à votre avis ? Un peu plus ? Deux fois plus ? Beaucoup plus ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Combien coûte la location du même bateau début 2024 ?",
          "options": [
            "25 000 dollars par jour.",
            "115 000 dollars par jour.",
            "1 million de dollars par jour."
          ],
          "bonne": 1,
          "explication": "« Début 2024, le même navire se loue <strong>115 000 dollars par jour</strong>. Neuf fois plus cher en trois ans. »"
        },
        {
          "q": "Après la crise de 2008, quelle leçon les propriétaires de bateaux ont-ils retenue ?",
          "options": [
            "Ne jamais construire un bateau sans être sûr d'avoir des clients.",
            "Construire beaucoup de bateaux très vite.",
            "Vendre tous leurs bateaux."
          ],
          "bonne": 0,
          "explication": "« Ne jamais construire un transporteur de voitures <strong>sur spéculation</strong> » : sans être sûr d'avoir des clients."
        }
      ],
      "trous": [
        {
          "avant": "Début 2024, le même navire se loue 115 000 dollars par jour. Neuf fois plus",
          "apres": "en trois ans.",
          "aide": "le contraire de « bon marché »",
          "reponses": [
            "cher"
          ],
          "solution": "cher"
        },
        {
          "avant": "Ne jamais construire un transporteur de voitures sur",
          "apres": ".",
          "aide": "= sans être sûr d'avoir des clients",
          "reponses": [
            "speculation"
          ],
          "solution": "spéculation"
        }
      ],
      "difficile": {
        "debut": 73.52,
        "fin": 84.3,
        "texte": "Les grands nombres passent très vite : « douze mille cinq cents », « cent quinze mille ». Astuce : écoutez le <strong>premier mot</strong> (« douze », « cent »), puis le <strong>dernier</strong> (« cents », « mille »). Le reste se déduit."
      }
    },
    {
      "id": "B",
      "titre": "Le vrai risque",
      "debut": 989.88,
      "fin": 1025.1,
      "pourquoi": "Le narrateur présente l'argument contraire, puis sa conséquence. Vous allez faire la même chose dans votre réponse.",
      "devine": "BYD a acheté ses propres bateaux au lieu de les louer. À votre avis, quel est le <strong>grand risque</strong> de cette décision ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Quel est le vrai risque, selon le narrateur ?",
          "options": [
            "Les bateaux sont trop petits.",
            "Un bateau engage l'entreprise pour 25 ans, et personne ne sait si la demande restera forte.",
            "Les voitures électriques sont trop lourdes."
          ],
          "bonne": 1,
          "explication": "« Un navire, c'est un <strong>engagement sur 25 ans</strong>. » Personne ne peut prédire la demande aussi loin."
        },
        {
          "q": "S'il y a bientôt trop de bateaux, qui aura eu raison ?",
          "options": [
            "Les entreprises qui ont acheté beaucoup de bateaux.",
            "Les entreprises qui sont restées flexibles (qui louent).",
            "Personne."
          ],
          "bonne": 1,
          "explication": "« La location redevient bon marché, et <strong>ceux qui sont restés flexibles</strong> auront eu raison. »"
        }
      ],
      "trous": [
        {
          "avant": "Reste le vrai contre-argument. Un navire, c'est un",
          "apres": "sur 25 ans.",
          "aide": "= une promesse qui oblige, pour longtemps",
          "reponses": [
            "engagement"
          ],
          "solution": "engagement"
        },
        {
          "avant": "Ceux qui sont restés",
          "apres": "auront eu raison.",
          "aide": "= qui peuvent changer facilement",
          "reponses": [
            "flexibles",
            "flexible"
          ],
          "solution": "flexibles"
        }
      ],
      "difficile": {
        "debut": 1002.94,
        "fin": 1010.6,
        "texte": "Deux situations opposées : « <strong>en pleine pénurie</strong> » (il manque des bateaux) et « <strong>en pleine surabondance</strong> » (il y en a trop). La voix monte sur la première, puis descend sur la seconde. « Des coûts fixes » = des dépenses qu'on paie chaque mois, même sans activité."
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour présenter la situation",
      "forme": "Pendant des années, la règle était simple : …",
      "film": {
        "texte": "<strong>Pendant 100 ans, la règle était simple.</strong> Les constructeurs fabriquent les voitures, les compagnies maritimes les transportent.",
        "t": 16,
        "debut": 15.66,
        "fin": 21.53,
        "contour": [
          -0.1,
          0.9,
          2.8,
          5.1,
          6.2,
          6.2,
          5.6,
          4.7,
          3.8,
          2.9,
          2.1,
          -0.2,
          -1.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.2,
          -2.4,
          -1.9,
          3.4,
          3.7,
          2.6,
          0.9,
          -0.3,
          -1.5,
          -2.8,
          -4.1,
          -4.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -6.6,
          -6.3,
          -6.2,
          -3.9,
          -1.6,
          -1.8,
          -2.5,
          -2.4,
          -2.2,
          -2.1,
          -3.4,
          -3.1,
          -2.7,
          -2.4,
          -3.5,
          -5.0,
          -5.3,
          -5.7,
          -6.2,
          -6.6,
          -7.0,
          -7.5,
          -7.9,
          -7.7,
          -7.3,
          -6.9,
          -6.5,
          -6.9,
          -7.0,
          -3.5,
          -3.1,
          -1.3,
          0.4,
          2.2,
          2.8,
          4.2,
          5.5,
          6.3,
          6.3,
          6.2,
          2.3,
          -1.5,
          -5.4,
          -9.3,
          -5.0,
          -4.7,
          -1.8,
          1.2,
          4.1,
          4.0,
          3.4,
          3.5,
          2.0,
          1.0,
          0.4,
          -0.3,
          -0.7,
          -2.4,
          -4.2,
          -5.9,
          -6.0,
          -5.8,
          -2.8,
          0.1,
          3.1,
          4.4,
          4.1,
          1.9,
          -1.2,
          9.3,
          4.5,
          0.8,
          -0.6,
          -1.9,
          -2.8
        ],
        "etendue": 13.5
      },
      "exemple": "Pendant des années, la règle était simple : un prestataire gérait notre informatique, et nous faisions notre métier.",
      "detect": [
        "la regle etait simple"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour dire ce qui est le plus grave",
      "forme": "… n'est pas le pire. Le pire, c'est…",
      "film": {
        "texte": "Mais l'argent <strong>n'est pas le pire. Le pire, c'est</strong> le contrôle.",
        "t": 196,
        "debut": 195.74,
        "fin": 198.89,
        "contour": [
          -2.6,
          -2.4,
          -1.6,
          -1.3,
          -1.2,
          -1.5,
          -1.4,
          -0.4,
          -0.1,
          -0.5,
          -0.8,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          4.2,
          4.8,
          5.5,
          6.4,
          7.2,
          7.4,
          6.8,
          5.3,
          4.3,
          -0.3,
          -2.3,
          -2.6,
          -2.6,
          -1.6,
          -0.6,
          0.4,
          1.4,
          2.4,
          3.4,
          3.0,
          2.8,
          1.3,
          0.4,
          -0.5,
          -1.6,
          -2.7,
          -2.8,
          -2.9,
          -2.5,
          -0.4,
          1.7,
          3.8,
          5.9,
          8.0,
          8.1,
          8.2,
          8.3,
          8.1,
          7.3,
          9.1,
          12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.8,
          -3.8,
          -3.7,
          -3.7,
          -3.7,
          -3.7,
          -3.9,
          -4.3,
          -4.4,
          -2.9,
          -1.4,
          0.2,
          1.7,
          3.2,
          4.7,
          5.6,
          6.6,
          7.4,
          7.8,
          8.5,
          8.9,
          8.1,
          7.4,
          6.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -2.0,
          -1.0,
          -0.5
        ],
        "etendue": 12.1
      },
      "exemple": "Le prix n'est pas le pire. Le pire, c'est d'attendre trois semaines chaque fois que nous avons besoin d'eux.",
      "detect": [
        "n est pas le pire",
        "le pire c est"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour insister sur un point important",
      "forme": "Ce n'est pas un détail, c'est…",
      "film": {
        "texte": "<strong>Ce n'est pas un détail, c'est</strong> le problème.",
        "t": 768,
        "debut": 768.28,
        "fin": 771.05,
        "contour": [
          -0.3,
          -0.4,
          -0.4,
          -0.3,
          -0.1,
          0.1,
          0.1,
          0.0,
          -0.0,
          2.7,
          5.5,
          8.2,
          8.2,
          8.1,
          8.0,
          6.8,
          6.2,
          5.7,
          5.1,
          5.1,
          4.9,
          4.5,
          3.9,
          3.8,
          3.1,
          2.9,
          2.8,
          2.5,
          2.3,
          3.1,
          3.8,
          4.6,
          4.3,
          3.7,
          3.1,
          2.4,
          1.3,
          -0.7,
          -1.5,
          -2.1,
          -3.2,
          -4.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -1.2,
          -1.5,
          -1.7,
          -2.0,
          -2.4,
          -2.6,
          -2.7,
          -2.7,
          -2.8,
          -2.8,
          -2.6,
          -2.3,
          -1.8,
          -1.2,
          -0.4,
          0.3,
          1.1,
          1.8,
          2.7,
          4.1,
          5.0,
          5.6,
          6.0,
          6.4,
          6.9,
          7.7,
          8.3,
          8.3,
          7.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.2,
          -0.3,
          -0.7,
          -1.4,
          -1.8,
          -2.0,
          -2.8,
          -3.1,
          -3.3,
          -3.7,
          -4.2,
          0.8,
          5.8,
          -6.4,
          -7.4,
          -7.9
        ],
        "etendue": 12.3
      },
      "exemple": "Ce n'est pas un détail, c'est notre relation avec les clients.",
      "detect": [
        "ce n est pas un detail"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour poser une condition",
      "forme": "Tant que…, …",
      "film": {
        "texte": "<strong>Tant que</strong> les volumes doublent chaque année et que la priorité est de battre les échéances tarifaires, le calcul se défend.",
        "t": 798,
        "debut": 797.92,
        "fin": 803.95,
        "contour": [
          5.7,
          4.6,
          3.7,
          6.6,
          9.5,
          5.3,
          -1.1,
          -2.8,
          -2.7,
          -0.3,
          -0.5,
          -1.6,
          -1.7,
          0.2,
          4.2,
          -3.8,
          -3.5,
          -1.8,
          5.9,
          7.4,
          3.6,
          0.7,
          -0.3,
          -1.8,
          0.5,
          2.8,
          5.1,
          4.5,
          3.0,
          1.5,
          0.2,
          0.2,
          1.4,
          3.6,
          6.3,
          8.2,
          6.3,
          2.6,
          -1.0,
          -2.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          -0.3,
          -1.3,
          -1.3,
          -1.1,
          3.5,
          8.1,
          12.0,
          6.2,
          -3.3,
          -4.4,
          -5.3,
          -5.5,
          -4.3,
          1.6,
          2.3,
          1.9,
          0.1,
          -1.6,
          -3.4,
          -5.2,
          -5.7,
          -5.7,
          -3.0,
          -0.1,
          0.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          4.4,
          3.2,
          -2.2,
          -2.6,
          -3.4,
          -2.3,
          -1.1,
          0.0,
          1.2,
          3.4,
          4.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -2.3,
          -1.7,
          5.4,
          7.0,
          8.4,
          12.0,
          -3.2,
          -3.5,
          -4.0,
          -0.0,
          3.9,
          3.7,
          2.5,
          2.2,
          1.9,
          1.6,
          11.1,
          4.0,
          -1.5,
          -2.3
        ],
        "etendue": 17.6
      },
      "exemple": "Tant que le prestataire répond vite, le calcul se défend.",
      "detect": [
        "tant que"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour présenter l'argument contraire",
      "forme": "Reste le vrai contre-argument : …",
      "film": {
        "texte": "<strong>Reste le vrai contre-argument.</strong> Un navire, c'est un engagement sur 25 ans.",
        "t": 990,
        "debut": 989.88,
        "fin": 994.61,
        "contour": [
          4.7,
          6.7,
          7.5,
          6.6,
          5.6,
          4.7,
          3.8,
          2.8,
          1.9,
          12.0,
          -1.3,
          -1.5,
          -2.1,
          -3.1,
          -4.5,
          -5.0,
          -3.0,
          -1.0,
          1.0,
          3.0,
          3.6,
          4.8,
          4.7,
          4.2,
          2.8,
          1.4,
          0.0,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -6.2,
          -6.6,
          -7.8,
          -8.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          3.8,
          4.5,
          6.3,
          6.9,
          6.7,
          5.6,
          3.0,
          0.3,
          -9.9,
          -12.0,
          -2.6,
          -1.8,
          -0.2,
          2.9,
          4.8,
          4.8,
          4.7,
          3.1,
          1.4,
          -0.2,
          -1.8,
          -3.4,
          -5.1,
          -6.7,
          -6.6,
          -5.8,
          -4.5,
          -0.9,
          1.2,
          1.4,
          0.4,
          -2.3,
          -2.8,
          -4.3,
          -4.8,
          -4.1,
          -3.4,
          -2.6,
          -0.9,
          1.1,
          3.1,
          3.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.0,
          0.9,
          1.2,
          1.3,
          0.4,
          -0.4,
          -1.3,
          -2.2,
          -3.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -6.9,
          -6.8
        ],
        "etendue": 13.8
      },
      "exemple": "Reste le vrai contre-argument : recruter une équipe, c'est un engagement sur plusieurs années.",
      "detect": [
        "contre argument",
        "reste le vrai"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour conclure en une phrase",
      "forme": "Retirez toutes les nuances, et voici ce qui reste : …",
      "film": {
        "texte": "Mais <strong>retirez toutes les nuances et voici ce qui reste.</strong>",
        "t": 1041,
        "debut": 1040.9,
        "fin": 1043.95,
        "contour": [
          -4.5,
          -4.3,
          -3.9,
          -3.4,
          -3.4,
          -3.5,
          -3.7,
          -3.8,
          -3.9,
          -2.8,
          -1.6,
          -0.5,
          0.6,
          1.7,
          2.9,
          4.0,
          5.0,
          5.9,
          6.7,
          6.9,
          6.7,
          6.6,
          6.6,
          6.7,
          6.8,
          6.9,
          7.0,
          7.1,
          7.2,
          7.3,
          7.1,
          6.8,
          6.7,
          6.2,
          5.8,
          5.8,
          5.8,
          5.7,
          5.3,
          5.2,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          6.6,
          6.4,
          6.1,
          5.8,
          5.5,
          5.2,
          4.8,
          4.5,
          4.2,
          4.3,
          12.0,
          12.0,
          8.2,
          1.6,
          0.6,
          0.4,
          -0.4,
          -0.7,
          -1.5,
          -2.8,
          -3.8,
          -4.5,
          -5.1,
          -5.4,
          -5.6,
          -5.6,
          -5.6,
          -5.4,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.7,
          -5.7,
          -5.6,
          -5.6,
          -5.8,
          -6.5,
          -6.9,
          -6.2,
          -5.4,
          -4.7,
          -4.1,
          -2.4,
          -1.0,
          -0.2,
          0.0,
          0.0,
          0.0
        ],
        "etendue": 12.8
      },
      "exemple": "Retirez toutes les nuances, et voici ce qui reste : nous gagnons en contrôle, mais nous perdons en souplesse.",
      "detect": [
        "retirez toutes les nuances",
        "voici ce qui reste",
        "si on retire"
      ]
    }
  ],
  "prononciation": {
    "intro": "Pour <strong>opposer deux idées</strong>, le français utilise la mélodie : la voix <strong>monte</strong> à la fin de la première idée, puis <strong>descend</strong> à la fin de la seconde.",
    "regle": [
      "Première idée : la voix <strong>monte ↗</strong> sur la dernière syllabe.",
      "Une petite pause.",
      "Seconde idée : la voix <strong>descend ↘</strong> sur la dernière syllabe. C'est l'idée la plus importante."
    ],
    "attention": "Si votre voix descend dès la première idée, votre interlocuteur croit que vous avez fini de parler… et il vous coupe la parole.",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "Mais l'ar·gent n'est pas le *pire. Le pire, c'est le con·*trôle.",
        "consigne": "Deux idées opposées. Cliquez sur la dernière syllabe de chaque idée (2 syllabes), puis vérifiez.",
        "explication": "« pire » : la voix monte (l'idée continue). « trôle » : la voix descend (c'est l'idée importante).",
        "debut": 195.74,
        "fin": 198.89
      },
      {
        "titre": "Phrase 2",
        "phrase": "Un na·vire af·fré·té est une fa·*veur. Un na·vire pos·sé·dé est un *fait.",
        "consigne": "Même chose : cliquez sur la dernière syllabe de chaque idée (2 syllabes), puis vérifiez.",
        "explication": "« veur » : la voix monte. « fait » : la voix descend. Louer (« affréter ») s'oppose à posséder.",
        "debut": 518.92,
        "fin": 523.23
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue"
      ],
      [
        "|",
        "fin d'un groupe"
      ],
      [
        "‿",
        "on enchaîne, sans pause"
      ],
      [
        "[t]",
        "on ajoute le son « t » (est une → « est-t-une »)"
      ]
    ],
    "modeles": [
      {
        "texte": "Mais l'argent n'est pas le <strong>pire</strong> ↗ | Le pire, c'est le con<strong>trôle</strong> ↘",
        "t": 196,
        "debut": 195.74,
        "fin": 198.89,
        "contour": [
          -2.6,
          -2.4,
          -1.6,
          -1.3,
          -1.2,
          -1.5,
          -1.4,
          -0.4,
          -0.1,
          -0.5,
          -0.8,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          4.2,
          4.8,
          5.5,
          6.4,
          7.2,
          7.4,
          6.8,
          5.3,
          4.3,
          -0.3,
          -2.3,
          -2.6,
          -2.6,
          -1.6,
          -0.6,
          0.4,
          1.4,
          2.4,
          3.4,
          3.0,
          2.8,
          1.3,
          0.4,
          -0.5,
          -1.6,
          -2.7,
          -2.8,
          -2.9,
          -2.5,
          -0.4,
          1.7,
          3.8,
          5.9,
          8.0,
          8.1,
          8.2,
          8.3,
          8.1,
          7.3,
          9.1,
          12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.8,
          -3.8,
          -3.7,
          -3.7,
          -3.7,
          -3.7,
          -3.9,
          -4.3,
          -4.4,
          -2.9,
          -1.4,
          0.2,
          1.7,
          3.2,
          4.7,
          5.6,
          6.6,
          7.4,
          7.8,
          8.5,
          8.9,
          8.1,
          7.4,
          6.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -2.0,
          -1.0,
          -0.5
        ],
        "etendue": 12.1
      },
      {
        "texte": "Un navire affrété est[t]une fa<strong>veur</strong> ↗ | Un navire possédé est[t]un <strong>fait</strong> ↘",
        "t": 519,
        "debut": 518.92,
        "fin": 523.23,
        "contour": [
          -5.9,
          -5.8,
          -5.4,
          -4.2,
          -2.4,
          -0.6,
          0.4,
          0.9,
          1.0,
          1.8,
          3.1,
          5.1,
          5.0,
          2.4,
          1.6,
          1.0,
          0.6,
          0.2,
          -0.1,
          -0.5,
          -0.8,
          -1.2,
          -1.6,
          -0.4,
          0.8,
          2.0,
          3.2,
          3.9,
          4.7,
          5.3,
          12.0,
          12.0,
          12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          2.4,
          2.5,
          2.5,
          2.3,
          1.5,
          1.4,
          1.4,
          1.3,
          1.2,
          1.2,
          1.1,
          0.5,
          -0.3,
          -1.6,
          -2.5,
          -2.5,
          -2.2,
          -2.3,
          -3.2,
          -4.1,
          -5.3,
          -6.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.7,
          -5.3,
          -4.4,
          -3.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          7.2,
          7.3,
          6.9,
          6.3,
          5.1,
          4.0,
          2.8,
          1.6,
          0.7,
          -1.1,
          -2.4,
          -2.7,
          -2.5,
          -2.0,
          -1.2,
          0.6,
          3.1,
          3.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -4.8,
          -4.9
        ],
        "etendue": 12.9
      },
      {
        "texte": "Ce n'est pas un dé<strong>tail</strong> ↗ | c'est le pro<strong>blème</strong> ↘",
        "t": 768,
        "debut": 768.28,
        "fin": 771.05,
        "contour": [
          -0.3,
          -0.4,
          -0.4,
          -0.3,
          -0.1,
          0.1,
          0.1,
          0.0,
          -0.0,
          2.7,
          5.5,
          8.2,
          8.2,
          8.1,
          8.0,
          6.8,
          6.2,
          5.7,
          5.1,
          5.1,
          4.9,
          4.5,
          3.9,
          3.8,
          3.1,
          2.9,
          2.8,
          2.5,
          2.3,
          3.1,
          3.8,
          4.6,
          4.3,
          3.7,
          3.1,
          2.4,
          1.3,
          -0.7,
          -1.5,
          -2.1,
          -3.2,
          -4.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -1.2,
          -1.5,
          -1.7,
          -2.0,
          -2.4,
          -2.6,
          -2.7,
          -2.7,
          -2.8,
          -2.8,
          -2.6,
          -2.3,
          -1.8,
          -1.2,
          -0.4,
          0.3,
          1.1,
          1.8,
          2.7,
          4.1,
          5.0,
          5.6,
          6.0,
          6.4,
          6.9,
          7.7,
          8.3,
          8.3,
          7.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.2,
          -0.3,
          -0.7,
          -1.4,
          -1.8,
          -2.0,
          -2.8,
          -3.1,
          -3.3,
          -3.7,
          -4.2,
          0.8,
          5.8,
          -6.4,
          -7.4,
          -7.9
        ],
        "etendue": 12.3
      }
    ],
    "etapes": [
      "Écoutez la phrase 2 fois.",
      "Parlez <strong>en même temps</strong> que la voix, 2 fois.",
      "Enregistrez-vous seul·e et comparez les courbes."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "essais": [
      {
        "duree": 90,
        "consigne": "Parlez avec vos notes.",
        "ajout": "Pour l'essai 2, ajoutez : « <strong>… n'est pas le pire. Le pire, c'est…</strong> » et « <strong>Ce n'est pas un détail, c'est…</strong> »."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur vous interrompt une fois. Répondez avec : « <strong>Je suis d'accord sur…, mais…</strong> »",
        "ajout": "Pour l'essai 3, terminez par : « <strong>Retirez toutes les nuances, et voici ce qui reste : …</strong> ». Et opposez vos idées avec la voix : elle monte ↗, puis elle descend ↘."
      },
      {
        "duree": 60,
        "consigne": "Sans vos notes. Seulement l'essentiel.",
        "ajout": ""
      }
    ],
    "objections": [
      "Nous n'avons pas les compétences en interne.",
      "Recruter une équipe prend au moins six mois.",
      "Le prestataire connaît déjà très bien nos dossiers.",
      "Et si l'activité baisse l'année prochaine ?"
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Répétez les 3 phrases de la mélodie avec la vidéo, en même temps que la voix (5 minutes)."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites les 6 phrases utiles sans regarder (bouton « Vérifier sans regarder »)."
    },
    {
      "jour": "Jour 3",
      "tache": "Dites votre phrase de la semaine dans une vraie réunion ou un vrai appel."
    },
    {
      "jour": "Jour 4",
      "tache": "Enregistrez 1 minute sur le sujet du jour et envoyez-la à votre formateur."
    }
  ],
  "voix": {
    "neuronale": "fr-FR-RemyMultilingualNeural",
    "dossiers": {
      "formateur": "audio/formateur/",
      "neuronale": "audio/neuronal/"
    }
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Choisissez le sujet ensemble pendant la discussion libre (champ « Mon sujet » : un travail que l'entreprise confie, ou pourrait confier, à un prestataire). 1 minute, sans correction."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute la vidéo",
        "role": "Débit rapide (environ 177 mots/min, 35 % plus vite que le film ARTE). Faites deviner avant chaque écoute. Le passage difficile se réécoute seul."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Vidéo → répétition → phrase personnelle. Faites adapter l'exemple au secteur de l'apprenant."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Cible : opposer deux idées (montée, puis descente). Syllabes à cliquer, puis shadowing et comparaison des courbes."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Jouez l'interlocuteur. À l'essai 2, lisez une objection. Retour entre les essais : 2 points au maximum."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même sujet qu'au début. Commentez les 3 chiffres avec l'apprenant."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une réunion réelle, une date."
      }
    ],
    "notes": [
      "Vidéo : narration d'une chaîne de vulgarisation (ElecTruc), voix humaine selon votre écoute du 24/09/2026, avec une musique de fond. Registre écrit-oral rapide, de type « enquête ».",
      "La transcription automatique de YouTube écorche « BYD » (« Bwedy », « Biwedi »…) : dans la vidéo, le nom est épelé à la française, « B-Y-D ».",
      "Vocabulaire à expliquer si besoin : affréter (= louer un bateau), armateur (= propriétaire de bateaux), flotte, coûts fixes, surcapacité.",
      "Incitez l'apprenant à se corriger (« Pardon ? », « Et la voix, elle monte ou elle descend ? ») plutôt que de donner la bonne forme.",
      "La vitesse « un peu plus lent » (0,9×) n'apparaît que si YouTube la propose pour cette vidéo."
    ]
  }
};
