/* =====================================================================
   SÉANCE IMPACT 60 (format 45 minutes) — FICHIER DE CONTENU
   Atelier : C'est quoi l'alimentation du futur ? (1 jour, 1 question)
   Tout ce qui suit « window.IMPACT60 = » doit rester du JSON strict.
   Mode d'emploi : MODELE_IMPACT60.md
   ===================================================================== */
window.IMPACT60 = {
  "meta": {
    "id": "alimentation-futur-a2-v1",
    "lien": "https://orionside.github.io/Atelier_Formation_Francais/Atelier_Alimentation_Futur_A2/",
    "titre": "Alimentation du futur",
    "niveau": "A2+",
    "duree": 45,
    "support": {
      "le": "la vidéo",
      "du": "de la vidéo",
      "dans": "dans la vidéo",
      "Le": "La vidéo"
    },
    "titreSeance": "Dire ce qui change… et pourquoi c'est bien",
    "objectif": "Aujourd'hui, vous apprenez à <strong>dire ce qui change</strong> dans vos habitudes (de plus en plus, de moins en moins) et à <strong>expliquer pourquoi c'est bien</strong>. En 1 minute, comme à table avec un collègue.",
    "video": {
      "url": "https://youtu.be/e4pOuOy6lpE",
      "titre": "C'est quoi l'alimentation du futur ? (1 jour, 1 question)",
      "duree": "1 min 42"
    },
    "plusLoin": [
      {
        "label": "Regarder la vidéo en entier (1 min 42)",
        "url": "https://youtu.be/e4pOuOy6lpE"
      }
    ]
  },
  "sujet": {
    "lieu": "À la cantine, à midi",
    "qui": "Un collègue français",
    "dit": "« Moi, je mange de moins en moins de viande. Et vous, qu'est-ce qui change dans votre assiette ? »",
    "vous": "Vous répondez : ce que vous mangez d'habitude, ce qui change, et pourquoi c'est bien. Puis vous posez une question à votre collègue.",
    "consigne": "Parlez de vos habitudes à table, et de ce qui change.",
    "perso": {
      "question": "Vous préférez parler d'une autre habitude ?",
      "exemple": "ex. : le sport, les transports, le télétravail",
      "phrase": "Votre collègue vous demande : « Et vous, qu'est-ce qui change ? » Parlez de : {x}. Dites votre habitude, ce qui change, et pourquoi c'est bien."
    },
    "plan": [
      {
        "titre": "Mon habitude",
        "aide": "J'ai l'habitude de manger…"
      },
      {
        "titre": "Ce qui change",
        "aide": "Je mange de plus en plus de… / de moins en moins de…"
      },
      {
        "titre": "Pourquoi c'est bien",
        "aide": "Ça permet de…"
      },
      {
        "titre": "Ma question",
        "aide": "Et vous, vous avez déjà essayé ?"
      }
    ]
  },
  "difficultes": [
    "Je cherchais mes mots",
    "Je ne savais pas comment commencer",
    "Je ne savais pas dire « de plus en plus »",
    "Je n'étais pas sûr·e de ma prononciation",
    "Rien de spécial"
  ],
  "ecoute": [
    {
      "id": "A",
      "titre": "Demain, dans nos assiettes",
      "debut": 12.16,
      "fin": 57.81,
      "pourquoi": "La voix explique ce qui va changer dans notre assiette, et pourquoi. Vous allez faire la même chose avec vos habitudes.",
      "devine": "À votre avis, qu'est-ce qu'on va manger dans 20 ans ? Répondez à voix haute : 2 idées.",
      "questions": [
        {
          "q": "Quel est le problème avec la viande et le maïs ?",
          "options": [
            "Ils coûtent trop cher.",
            "Ils demandent beaucoup d'eau.",
            "Ils n'ont pas de goût."
          ],
          "bonne": 1,
          "explication": "La voix dit : « des produits qui, comme la viande ou le maïs, <strong>nécessitent beaucoup d'eau</strong> ». Nécessiter = avoir besoin de (necesitar)."
        },
        {
          "q": "Où peut-on trouver des protéines, sans manger de viande ?",
          "options": [
            "Dans le chocolat et la farine.",
            "Dans l'eau.",
            "Dans des plantes comme le soja, et dans les insectes."
          ],
          "bonne": 2,
          "explication": "« On peut en trouver ailleurs, <strong>dans des plantes comme le soja, mais aussi dans les insectes</strong>. » Ailleurs = dans un autre endroit."
        }
      ],
      "trous": [
        {
          "avant": "D'ici une vingtaine d'années, le contenu de nos assiettes va beaucoup",
          "apres": ".",
          "aide": "= être différent (cambiar)",
          "reponses": [
            "changer"
          ],
          "solution": "changer"
        },
        {
          "avant": "Manger des grillons au chocolat va devenir de plus en",
          "apres": "banal.",
          "aide": "ça augmente (cada vez más)",
          "reponses": [
            "plus"
          ],
          "solution": "plus"
        }
      ],
      "difficile": {
        "debut": 24.66,
        "fin": 30.09,
        "texte": "« Comment nourrir 8,5 milliards d'habitants en 2030 ? » Écoutez les deux nombres : <strong>8,5</strong> se dit « huit virgule cinq » et <strong>2030</strong> se dit « deux mille trente ». Nourrir = donner à manger (alimentar). Un milliard = 1 000 000 000 (mil millones)."
      }
    },
    {
      "id": "B",
      "titre": "Moins d'eau, zéro déchet",
      "debut": 57.44,
      "fin": 96.7,
      "pourquoi": "La voix donne trois nouveautés. Pour chacune, elle dit pourquoi c'est bien… ou ce qui manque encore. C'est utile pour donner votre avis.",
      "devine": "Chez vous, qu'est-ce que vous faites avec les restes (= la nourriture non mangée) ? Répondez à voix haute.",
      "questions": [
        {
          "q": "Le steak fabriqué en laboratoire a-t-il le même goût que la vraie viande ?",
          "options": [
            "Oui, exactement le même goût.",
            "Non, pas encore.",
            "La vidéo ne le dit pas."
          ],
          "bonne": 1,
          "explication": "« Ce steak synthétique <strong>n'a pas encore la saveur de l'original</strong>. » La saveur = le goût. Synthétique = fabriqué, pas naturel."
        },
        {
          "q": "« Zéro déchet » : qu'est-ce que ça veut dire dans la vidéo ?",
          "options": [
            "On ne jette plus de nourriture : on cuisine les restes.",
            "On mange seulement des algues.",
            "On ne va plus au restaurant."
          ],
          "bonne": 0,
          "explication": "« Savoir inventer de nouvelles recettes pour <strong>récupérer les restes</strong>, c'est ça aussi la cuisine du futur. » Un déchet = une chose qu'on jette à la poubelle (un residuo)."
        }
      ],
      "trous": [
        {
          "avant": "Cette nouvelle technologie",
          "apres": "d'économiser beaucoup d'eau.",
          "aide": "= rend possible (permite)",
          "reponses": [
            "permet"
          ],
          "solution": "permet"
        },
        {
          "avant": "Un tiers de la production alimentaire mondiale est",
          "apres": "et perdue.",
          "aide": "= jetée, non utilisée (desperdiciada)",
          "reponses": [
            "gaspillee",
            "gaspille"
          ],
          "solution": "gaspillée"
        }
      ],
      "difficile": {
        "debut": 73.02,
        "fin": 78.22,
        "texte": "« La laitue sera remplacée par les algues, comme la nori ou le wakamé. » <strong>La laitue</strong> = la salade verte (la lechuga). <strong>Les algues</strong> = des plantes de la mer (las algas). « Nori » et « wakamé » sont deux algues japonaises. <strong>Sera</strong> = le verbe « être » au futur."
      }
    }
  ],
  "phrases": [
    {
      "id": "p1",
      "sert": "Pour annoncer un changement (va + verbe = bientôt)",
      "forme": "… va beaucoup changer.",
      "film": {
        "texte": "D'ici une vingtaine d'années, le contenu de nos assiettes <strong>va beaucoup changer</strong>.",
        "t": 13,
        "debut": 12.03,
        "fin": 18.29,
        "contour": [
          -9.8,
          -9.4,
          -2.6,
          -2.5,
          1.2,
          4.8,
          5.1,
          6.4,
          7.6,
          8.9,
          8.0,
          6.1,
          0.8,
          -3.6,
          -5.3,
          -7.7,
          -8.1,
          -7.6,
          -3.1,
          1.3,
          5.8,
          6.5,
          5.0,
          1.9,
          5.5,
          4.4,
          2.3,
          0.7,
          -2.1,
          -0.7,
          -1.3,
          -1.0,
          -0.9,
          0.0,
          2.2,
          3.4,
          1.3,
          -0.8,
          -2.9,
          -5.0,
          -7.1,
          -9.2,
          -8.9,
          -4.9,
          -0.8,
          -1.7,
          -2.7,
          -3.4,
          -3.5,
          -0.2,
          3.1,
          6.4,
          6.9,
          7.2,
          6.7,
          6.1,
          11.1,
          7.4,
          3.5,
          3.0,
          1.7,
          -3.5,
          -4.0,
          -5.4,
          -3.7,
          1.8,
          4.6,
          5.2,
          3.0,
          0.8,
          -0.5,
          -1.3,
          -0.2,
          0.9,
          2.0,
          1.7,
          2.8,
          3.6,
          2.3,
          1.0,
          -0.2,
          -1.5,
          -2.8,
          -4.1,
          -5.3,
          -5.2,
          -5.3,
          -5.5,
          -5.6,
          -5.6,
          -5.6,
          -5.6,
          -2.7,
          2.4,
          4.2,
          5.7,
          5.6,
          3.9,
          1.4,
          4.1,
          6.7,
          7.1,
          6.8,
          4.6,
          -0.9,
          -3.3,
          -6.2,
          -9.1,
          -12.0,
          -12.0,
          -3.6,
          -5.0,
          -6.4,
          -7.1,
          -8.4,
          -9.3,
          -10.2,
          -11.1,
          -12.0,
          -12.0
        ],
        "etendue": 16.9
      },
      "exemple": "Avec le nouveau logiciel, notre travail va beaucoup changer.",
      "detect": [
        "va beaucoup changer",
        "va changer"
      ]
    },
    {
      "id": "p2",
      "sert": "Pour dire que quelque chose augmente (le contraire : de moins en moins)",
      "forme": "… de plus en plus… / … de moins en moins…",
      "film": {
        "texte": "En Europe, manger des grillons au chocolat ou des vers de farine va devenir <strong>de plus en plus</strong> banal.",
        "t": 51,
        "debut": 50.08,
        "fin": 56.48,
        "contour": [
          -11.0,
          -10.4,
          -10.1,
          -7.7,
          -5.2,
          -2.8,
          -2.2,
          -1.4,
          -1.4,
          1.1,
          2.2,
          3.1,
          2.2,
          1.3,
          0.4,
          -0.4,
          -1.3,
          -2.2,
          -2.1,
          -0.7,
          1.2,
          1.8,
          0.6,
          1.6,
          2.0,
          -0.2,
          -1.4,
          -3.9,
          -5.9,
          -6.1,
          -4.3,
          -2.6,
          -0.8,
          0.9,
          3.0,
          3.3,
          1.5,
          -1.9,
          -4.5,
          -5.6,
          -1.5,
          2.5,
          2.0,
          0.3,
          1.9,
          1.6,
          1.2,
          0.3,
          -0.5,
          -1.4,
          -5.7,
          -5.4,
          -5.9,
          -7.0,
          -7.0,
          -7.5,
          -4.0,
          -4.5,
          -4.2,
          -4.5,
          -0.5,
          3.6,
          3.0,
          -2.5,
          -5.2,
          -3.6,
          -2.0,
          -0.3,
          1.3,
          2.9,
          3.9,
          4.9,
          1.8,
          -4.9,
          -7.3,
          -8.2,
          -9.1,
          -9.9,
          -10.8,
          -10.7,
          -10.3,
          -4.4,
          -4.0,
          -0.2,
          0.0,
          6.2,
          11.6,
          0.6,
          2.3,
          3.4,
          4.9,
          5.9,
          5.8,
          0.8,
          0.8,
          0.3,
          2.9,
          5.6,
          5.7,
          12.0,
          12.0,
          10.6,
          9.2,
          8.1,
          7.8,
          7.6,
          7.2,
          5.0,
          5.8,
          3.4,
          1.4,
          -4.9,
          -7.2,
          -8.9,
          -9.8,
          -10.1,
          -10.3,
          -10.6,
          -10.8,
          -10.1
        ],
        "etendue": 18.3
      },
      "exemple": "Je travaille de plus en plus à la maison, et de moins en moins au bureau.",
      "detect": [
        "de plus en plus",
        "de moins en moins"
      ]
    },
    {
      "id": "p3",
      "sert": "Pour parler d'une habitude (= ce qu'on fait souvent)",
      "forme": "J'ai l'habitude de… + verbe",
      "film": {
        "texte": "Les Africains et les Asiatiques <strong>ont</strong> depuis longtemps <strong>l'habitude de</strong> manger des chenilles, des termites ou des sauterelles.",
        "t": 44,
        "debut": 43.8,
        "fin": 50.5,
        "contour": [
          2.5,
          2.5,
          1.6,
          1.0,
          0.3,
          -0.3,
          -1.0,
          -1.6,
          -0.4,
          0.4,
          -1.3,
          1.8,
          0.7,
          -6.7,
          -8.3,
          1.6,
          0.5,
          -1.2,
          0.4,
          2.0,
          1.7,
          1.3,
          0.4,
          -2.8,
          -5.0,
          -5.5,
          -4.9,
          -3.1,
          -2.9,
          -3.7,
          -1.5,
          -2.8,
          -1.2,
          0.5,
          2.1,
          3.7,
          5.4,
          7.0,
          -2.1,
          -1.3,
          -0.6,
          0.2,
          0.1,
          -5.8,
          -0.1,
          0.0,
          -3.7,
          -7.5,
          -11.2,
          -5.7,
          1.8,
          5.1,
          -5.0,
          -11.1,
          0.5,
          12.0,
          9.2,
          5.4,
          8.9,
          -1.4,
          -1.1,
          0.2,
          -0.1,
          1.8,
          3.7,
          2.9,
          -0.6,
          -0.8,
          -1.0,
          -1.4,
          -0.8,
          -0.4,
          -7.8,
          -12.0,
          1.6,
          0.7,
          -1.0,
          -2.7,
          -2.9,
          -1.0,
          0.8,
          0.8,
          1.5,
          2.7,
          2.7,
          0.8,
          -2.2,
          -3.5,
          -2.7,
          -1.9,
          -0.2,
          0.5,
          1.3,
          2.0,
          0.3,
          1.4,
          3.0,
          4.2,
          4.8,
          4.1,
          2.1,
          0.1,
          -1.9,
          -1.8,
          -1.9,
          -2.4,
          -3.6,
          -4.5,
          -3.0,
          -1.4,
          -1.5,
          -0.2,
          1.1,
          0.8,
          -0.7,
          0.2,
          1.2,
          1.3,
          -0.4,
          -3.1
        ],
        "etendue": 11.7
      },
      "exemple": "J'ai l'habitude de déjeuner avec mon équipe le vendredi.",
      "detect": [
        "l habitude de",
        "l habitude d"
      ]
    },
    {
      "id": "p4",
      "sert": "Pour ne pas répéter un mot : « en » remplace « des protéines »",
      "forme": "On peut en trouver… / J'en mange…",
      "film": {
        "texte": "Or, <strong>on peut en trouver</strong> ailleurs, dans des plantes comme le soja, mais aussi dans les insectes.",
        "t": 39,
        "debut": 38.26,
        "fin": 44.63,
        "contour": [
          2.4,
          6.6,
          8.2,
          8.4,
          6.9,
          -0.3,
          -7.6,
          -10.7,
          -10.9,
          1.7,
          1.9,
          2.2,
          1.5,
          5.8,
          10.1,
          7.8,
          5.3,
          3.0,
          3.5,
          4.1,
          4.2,
          2.6,
          2.2,
          1.2,
          -1.7,
          -2.9,
          -2.4,
          -2.2,
          2.7,
          -1.8,
          -3.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -6.3,
          -7.0,
          -5.3,
          -5.8,
          -4.4,
          -3.0,
          -2.5,
          -2.1,
          -1.6,
          -1.8,
          -2.6,
          -3.5,
          -4.3,
          -5.2,
          -6.0,
          -3.8,
          -3.7,
          -3.7,
          -3.5,
          3.0,
          2.8,
          2.0,
          2.1,
          2.0,
          -0.8,
          -5.5,
          -7.1,
          -8.8,
          -10.4,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          2.2,
          2.9,
          3.9,
          4.5,
          4.1,
          5.4,
          6.8,
          6.4,
          2.2,
          -2.0,
          -6.1,
          -10.3,
          -10.0,
          -9.7,
          -4.4,
          -6.0,
          -6.2,
          -3.4,
          -2.7,
          0.8,
          3.5,
          5.7,
          3.4,
          0.7,
          -3.7,
          -4.2,
          -5.6,
          -5.5,
          -2.2,
          1.1,
          0.4,
          -0.4,
          -0.5,
          -0.6,
          -0.6,
          -0.7,
          -0.4,
          -0.3,
          -4.2,
          -8.0,
          -11.9,
          -0.7,
          0.3,
          0.4,
          0.5,
          0.4,
          0.0
        ],
        "etendue": 18.2
      },
      "exemple": "Du café ? J'en bois deux par jour. On peut en trouver au premier étage.",
      "detect": [
        "j en mange",
        "j en bois",
        "on peut en"
      ]
    },
    {
      "id": "p5",
      "sert": "Pour expliquer pourquoi c'est bien",
      "forme": "Ça permet de… + verbe",
      "film": {
        "texte": "Cette nouvelle technologie <strong>permet d'économiser</strong> beaucoup d'eau…",
        "t": 64,
        "debut": 63.62,
        "fin": 67.56,
        "contour": [
          -0.5,
          -1.1,
          -1.8,
          -2.5,
          -3.3,
          -4.0,
          -4.7,
          -5.5,
          -6.2,
          -6.0,
          -4.9,
          -2.6,
          0.5,
          2.3,
          2.5,
          2.5,
          2.4,
          1.8,
          0.2,
          -1.4,
          -3.0,
          -3.2,
          -1.7,
          -0.1,
          1.4,
          1.5,
          1.1,
          -0.6,
          -0.4,
          -0.2,
          0.0,
          -0.3,
          -1.2,
          -1.8,
          -2.1,
          -2.1,
          -2.1,
          -2.5,
          -2.8,
          -1.0,
          0.9,
          2.7,
          2.8,
          2.2,
          1.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.7,
          -4.9,
          -4.2,
          -3.8,
          -3.8,
          -5.7,
          -5.7,
          1.0,
          1.9,
          2.4,
          1.7,
          -0.6,
          -0.8,
          2.1,
          2.0,
          1.3,
          0.6,
          1.1,
          1.0,
          0.4,
          0.3,
          0.5,
          0.5,
          -0.2,
          -1.3,
          -2.2,
          1.1,
          1.1,
          0.9,
          -1.2,
          -4.2,
          -4.4,
          -3.0,
          -1.8,
          4.0,
          4.2,
          4.0,
          3.8,
          3.5,
          3.3,
          3.3,
          2.9,
          2.7,
          2.7,
          2.0,
          0.8,
          -0.3,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.6,
          -5.4,
          -5.1
        ],
        "etendue": 8.8
      },
      "exemple": "Le télétravail, ça permet de gagner du temps.",
      "detect": [
        "permet de",
        "permet d"
      ]
    },
    {
      "id": "p6",
      "sert": "Pour poser une question à l'autre (« tu » avec un ami, « vous » au travail)",
      "forme": "Tu as déjà essayé ? / Vous avez déjà essayé ?",
      "film": {
        "texte": "<strong>Tu as déjà essayé ?</strong>",
        "t": 56,
        "debut": 55.8,
        "fin": 57.94,
        "contour": [
          -10.1,
          -10.1,
          -10.0,
          -9.9,
          -9.9,
          -9.5,
          -9.4,
          -9.2,
          -9.2,
          -9.2,
          -9.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          7.2,
          6.5,
          5.8,
          5.8,
          5.1,
          4.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          3.5,
          3.4,
          3.3,
          3.3,
          3.3,
          1.8,
          0.3,
          -1.2,
          -1.3,
          -1.5,
          -1.9,
          -2.3,
          -2.3,
          -2.3,
          -2.0,
          -2.0,
          0.0,
          1.2,
          1.5,
          1.5,
          1.5,
          1.2,
          1.0,
          0.9,
          0.8,
          0.0,
          -0.7,
          -1.5,
          -2.3,
          -1.6,
          -0.9,
          -0.1,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          -0.1,
          -0.9,
          -1.0,
          -1.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.1,
          -0.3,
          -0.5,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0
        ],
        "etendue": 25.5
      },
      "exemple": "Il y a un nouveau restaurant japonais. Vous avez déjà essayé ?",
      "detect": [
        "deja essaye",
        "vous avez deja",
        "tu as deja"
      ]
    }
  ],
  "prononciation": {
    "intro": "En français, la voix <strong>monte ↗</strong> sur le mot qui dit « combien » : <strong>beaucoup</strong>, <strong>plus</strong>. Puis elle <strong>descend ↘</strong> à la fin de la phrase.",
    "regle": [
      "Vous dites « beaucoup » ou « de plus en plus » : la voix <strong>monte ↗</strong> sur ce mot. C'est le mot important.",
      "« De plus en plus » : la voix monte sur le <strong>premier</strong> « plus ».",
      "C'est la fin de la phrase : la voix <strong>descend ↘</strong>. L'autre sait que c'est à lui de parler."
    ],
    "attention": "La dernière syllabe du mot est plus longue : beau<strong>coup</strong>, chan<strong>ger</strong>, ba<strong>nal</strong>. Attention : toutes les questions ne montent pas. Dans la vidéo, « Tu as déjà essayé ? » <strong>descend</strong>. Les flèches ↗ ↘ montrent la mélodie <strong>mesurée</strong> dans la vidéo.",
    "perception": [
      {
        "titre": "Phrase 1",
        "phrase": "… va de·ve·nir de *plus en plus ba·nal.",
        "consigne": "Écoutez la fin de la phrase. Sur quelle syllabe la voix monte-t-elle le plus haut ? Cliquez sur 1 syllabe, puis vérifiez.",
        "explication": "La voix monte sur le premier « plus » : c'est le mot important. Sur « banal », elle descend : la phrase est finie.",
        "debut": 53.58,
        "fin": 56.48
      },
      {
        "titre": "Phrase 2",
        "phrase": "… per·met d'é·co·no·mi·ser beau·*coup d'eau.",
        "consigne": "Écoutez. Sur quelle syllabe la voix monte-t-elle ? Cliquez sur 1 syllabe, puis vérifiez.",
        "explication": "La voix monte sur « -coup » de « beaucoup » : c'est le mot qui dit « combien ».",
        "debut": 64.96,
        "fin": 67.56
      }
    ],
    "legende": [
      [
        "↗",
        "la voix monte (mesuré dans la vidéo)"
      ],
      [
        "↘",
        "la voix descend"
      ],
      [
        "souligné",
        "syllabe plus longue"
      ],
      [
        "|",
        "petite pause"
      ],
      [
        "‿",
        "on enchaîne, sans pause"
      ]
    ],
    "modeles": [
      {
        "texte": "Le contenu de nos‿assiettes va beau<strong>coup</strong> ↗ chan<strong>ger</strong> ↘",
        "t": 15,
        "debut": 14.08,
        "fin": 18.28,
        "contour": [
          -9.4,
          -9.4,
          -7.3,
          -5.2,
          -3.1,
          -1.0,
          -1.3,
          -2.4,
          -3.0,
          -3.6,
          -3.6,
          -3.7,
          -1.7,
          0.3,
          2.3,
          4.3,
          6.3,
          6.7,
          7.0,
          7.0,
          6.7,
          6.3,
          6.0,
          11.0,
          12.0,
          4.0,
          3.3,
          3.2,
          2.6,
          2.1,
          -0.1,
          -4.2,
          -4.2,
          -4.4,
          -5.9,
          -5.2,
          -1.8,
          2.2,
          3.9,
          5.0,
          5.0,
          3.6,
          2.1,
          0.7,
          0.0,
          -1.3,
          -1.5,
          -0.9,
          -0.2,
          0.4,
          1.1,
          1.7,
          1.5,
          1.8,
          3.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -3.9,
          -5.3,
          -5.5,
          -5.4,
          -5.5,
          -5.5,
          -5.6,
          -5.6,
          -5.7,
          -5.9,
          -5.9,
          -5.8,
          -5.8,
          -5.5,
          -2.1,
          1.6,
          3.0,
          3.9,
          5.4,
          5.5,
          5.4,
          5.1,
          2.2,
          1.4,
          3.1,
          4.8,
          6.5,
          6.7,
          7.0,
          6.6,
          5.5,
          2.9,
          -1.1,
          -3.3,
          -4.8,
          -6.2,
          -7.6,
          -9.1,
          -10.6,
          -12.0,
          -9.0,
          -8.3,
          -7.7,
          -7.1,
          -6.4,
          -7.0,
          -8.1,
          -8.6,
          -8.9,
          -9.7,
          -10.4,
          -11.2,
          -12.0,
          -12.0,
          -12.0,
          -12.0
        ],
        "etendue": 21.6
      },
      {
        "texte": "… va devenir de <strong>plus</strong> ↗ en plus ba<strong>nal</strong> ↘",
        "t": 54,
        "debut": 53.58,
        "fin": 56.48,
        "contour": [
          3.0,
          3.2,
          3.3,
          2.8,
          1.2,
          -1.3,
          -4.9,
          -7.6,
          -8.9,
          -9.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -11.9,
          -9.1,
          -6.2,
          -6.2,
          -6.1,
          -5.4,
          -2.6,
          -1.6,
          -1.8,
          -1.9,
          -1.0,
          -0.1,
          0.8,
          10.4,
          12.0,
          0.4,
          -1.2,
          -1.7,
          -1.2,
          0.2,
          1.1,
          1.5,
          1.5,
          1.9,
          2.9,
          3.7,
          4.1,
          4.0,
          4.0,
          2.8,
          1.5,
          0.2,
          -1.0,
          -1.0,
          -1.0,
          -1.4,
          -0.4,
          0.6,
          1.7,
          2.7,
          3.7,
          3.7,
          3.8,
          3.8,
          7.9,
          12.0,
          11.9,
          11.0,
          10.2,
          9.6,
          9.0,
          8.4,
          7.8,
          7.4,
          6.5,
          6.1,
          6.0,
          6.0,
          5.9,
          5.8,
          5.8,
          5.7,
          5.7,
          5.5,
          4.0,
          3.0,
          3.5,
          4.0,
          3.9,
          3.7,
          1.8,
          0.5,
          -0.5,
          -3.2,
          -6.0,
          -6.8,
          -8.2,
          -8.7,
          -9.7,
          -10.1,
          -11.2,
          -11.4,
          -11.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -11.9
        ],
        "etendue": 23.5
      },
      {
        "texte": "Cette nouvelle technologie permet d'économiser beau<strong>coup</strong> ↗ d'eau…",
        "t": 64,
        "debut": 63.62,
        "fin": 67.56,
        "contour": [
          -0.5,
          -1.1,
          -1.8,
          -2.5,
          -3.3,
          -4.0,
          -4.7,
          -5.5,
          -6.2,
          -6.0,
          -4.9,
          -2.6,
          0.5,
          2.3,
          2.5,
          2.5,
          2.4,
          1.8,
          0.2,
          -1.4,
          -3.0,
          -3.2,
          -1.7,
          -0.1,
          1.4,
          1.5,
          1.1,
          -0.6,
          -0.4,
          -0.2,
          0.0,
          -0.3,
          -1.2,
          -1.8,
          -2.1,
          -2.1,
          -2.1,
          -2.5,
          -2.8,
          -1.0,
          0.9,
          2.7,
          2.8,
          2.2,
          1.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.7,
          -4.9,
          -4.2,
          -3.8,
          -3.8,
          -5.7,
          -5.7,
          1.0,
          1.9,
          2.4,
          1.7,
          -0.6,
          -0.8,
          2.1,
          2.0,
          1.3,
          0.6,
          1.1,
          1.0,
          0.4,
          0.3,
          0.5,
          0.5,
          -0.2,
          -1.3,
          -2.2,
          1.1,
          1.1,
          0.9,
          -1.2,
          -4.2,
          -4.4,
          -3.0,
          -1.8,
          4.0,
          4.2,
          4.0,
          3.8,
          3.5,
          3.3,
          3.3,
          2.9,
          2.7,
          2.7,
          2.0,
          0.8,
          -0.3,
          -0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -5.6,
          -5.4,
          -5.1
        ],
        "etendue": 8.8
      },
      {
        "texte": "Tu as déjà essa<strong>yé</strong> ↘ ?",
        "t": 56,
        "debut": 55.8,
        "fin": 57.94,
        "contour": [
          -10.1,
          -10.1,
          -10.0,
          -9.9,
          -9.9,
          -9.5,
          -9.4,
          -9.2,
          -9.2,
          -9.2,
          -9.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          7.2,
          6.5,
          5.8,
          5.8,
          5.1,
          4.3,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          3.5,
          3.4,
          3.3,
          3.3,
          3.3,
          1.8,
          0.3,
          -1.2,
          -1.3,
          -1.5,
          -1.9,
          -2.3,
          -2.3,
          -2.3,
          -2.0,
          -2.0,
          0.0,
          1.2,
          1.5,
          1.5,
          1.5,
          1.2,
          1.0,
          0.9,
          0.8,
          0.0,
          -0.7,
          -1.5,
          -2.3,
          -1.6,
          -0.9,
          -0.1,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          0.2,
          -0.1,
          -0.9,
          -1.0,
          -1.1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          -0.1,
          -0.3,
          -0.5,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          -12.0,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0,
          12.0
        ],
        "etendue": 25.5
      }
    ],
    "etapes": [
      "Écoutez la phrase 2 fois.",
      "Parlez <strong>en même temps</strong> que la voix, 2 fois.",
      "Enregistrez-vous seul·e et comparez les courbes."
    ]
  },
  "entrainement": {
    "preparation": 60,
    "boutonObjection": "Question du collègue (pour le formateur)",
    "essais": [
      {
        "duree": 90,
        "consigne": "Parlez avec vos notes : votre habitude, ce qui change, pourquoi c'est bien, puis votre question.",
        "ajout": "Pour l'essai 2, ajoutez : « <strong>de plus en plus</strong> » et « <strong>de moins en moins</strong> ». Et faites monter la voix ↗ sur « plus » et sur « moins »."
      },
      {
        "duree": 75,
        "consigne": "Votre formateur joue le collègue et vous pose une question. Répondez.",
        "ajout": "Pour l'essai 3, ajoutez : « <strong>Ça permet de…</strong> » et finissez avec : « <strong>Et vous, vous avez déjà essayé ?</strong> »"
      },
      {
        "duree": 60,
        "consigne": "Sans vos notes. Seulement l'essentiel.",
        "ajout": ""
      }
    ],
    "objections": [
      "Et la viande, vous en mangez souvent ?",
      "Manger des insectes, vous avez déjà essayé ?",
      "Qu'est-ce que vous faites avec les restes ?",
      "Vous allez de plus en plus au restaurant, ou de moins en moins ?"
    ]
  },
  "semaine": [
    {
      "jour": "Jour 1",
      "tache": "Répétez les 4 phrases de la mélodie avec la vidéo, en même temps que la voix (5 minutes)."
    },
    {
      "jour": "Jour 2",
      "tache": "Dites les 6 phrases utiles sans regarder (bouton « Vérifier sans regarder »)."
    },
    {
      "jour": "Jour 3",
      "tache": "Dites à voix haute 2 choses que vous faites de plus en plus, et 2 choses que vous faites de moins en moins. Enregistrez-vous."
    },
    {
      "jour": "Jour 4",
      "tache": "Enregistrez 1 minute : vos habitudes à table, ce qui change, et pourquoi c'est bien. Envoyez-la à votre formateur."
    }
  ],
  "voix": {
    "neuronale": "fr-FR-RemyMultilingualNeural",
    "dossiers": {
      "formateur": "audio/formateur/",
      "neuronale": "audio/neuronal/"
    }
  },
  "formateur": {
    "deroule": [
      {
        "temps": "0–3",
        "phase": "Je parle 1 minute",
        "role": "Jouez le collègue : « Moi, je mange de moins en moins de viande. Et vous, qu'est-ce qui change dans votre assiette ? » 1 minute, sans correction. Pour un A2+, 5 à 7 phrases, c'est déjà bien."
      },
      {
        "temps": "3–11",
        "phase": "J'écoute la vidéo",
        "role": "Voix off claire, environ 168 mots/min : plus rapide que le dialogue du manuel. Faites deviner avant chaque écoute. Le passage difficile se réécoute seul."
      },
      {
        "temps": "11–20",
        "phase": "6 phrases utiles",
        "role": "Moitié « dire ce qui change » (p1, p2, p3), moitié « expliquer et échanger » (p4, p5, p6). Faites dire chaque phrase avec les habitudes réelles de l'apprenante. Ajoutez « de moins en moins » (manuel p. 57), qui n'est pas dans la vidéo."
      },
      {
        "temps": "20–26",
        "phase": "La mélodie",
        "role": "Cible : la voix monte ↗ sur « beaucoup » et sur le premier « plus », puis descend ↘ à la fin. Syllabes à cliquer, puis parler en même temps que la voix, puis courbes."
      },
      {
        "temps": "26–38",
        "phase": "Je m'entraîne 3 fois",
        "role": "Vous jouez le collègue. À l'essai 2, lisez une question (« Question du collègue »). Retour entre les essais : 2 points au maximum."
      },
      {
        "temps": "38–41",
        "phase": "Je reparle 1 minute",
        "role": "Même situation qu'au début. Commentez les 3 chiffres avec l'apprenante."
      },
      {
        "temps": "41–45",
        "phase": "Objectif de la semaine",
        "role": "Une phrase, une situation réelle (un déjeuner, une pause-café), une date."
      }
    ],
    "notes": [
      "Lien avec le manuel Défi actuel 2 (A2), unité 3 « Je me suis régalé ! » : p. 51 (parler d'une mode culinaire, le pronom « en », la progression « de plus en plus / de moins en moins », parler de ses habitudes alimentaires) et p. 56-57 (article « Les nouvelles tendances en cuisine » : cuisiner les restes, « ça permet de faire des économies et d'éviter le gaspillage alimentaire » ; pistes 38 et 39). La vidéo reprend les mêmes idées : « de plus en plus », « permet d'économiser », « gaspillée », « récupérer les restes », « restaurants japonais ».",
      "Ce qui est dans le manuel mais pas dans la vidéo : « de moins en moins » (ajouté dans les exemples, le plan et l'essai 2) et « lequel / laquelle » (p. 57, activités 9 à 11 : à travailler avec le manuel, par exemple « Insectes ou algues : lequel allez-vous goûter ? »).",
      "Vidéo : dessin animé « 1 jour, 1 question » (2018), une seule voix off humaine, environ 168 mots/min, phrases écrites. Elle tutoie (« Tu as déjà essayé ? ») parce qu'elle parle à des enfants : au travail, l'apprenante dit « Vous avez déjà essayé ? ». Écoutez la voix avant d'envoyer le lien, pour confirmer qu'elle vous convient comme modèle.",
      "Extraits : chaque phrase commence 0,6 s avant le premier mot et finit au moins 0,3 s après le dernier, puis a été retranscrite avec deux modèles Whisper (grand et petit), entière et sans ses 0,4 premières secondes : aucun mot ne manque. Dans les marges, on entend aussi « banal » avant « Tu as déjà essayé ? », et « mais… » après « beaucoup d'eau ».",
      "Mélodie mesurée (pas supposée) : dans « va beaucoup changer », la voix monte de 11 demi-tons sur « beaucoup », puis descend de 14 sur « changer » ; dans « de plus en plus banal », elle monte de 12 demi-tons sur le premier « plus », puis descend de 14 sur « banal » ; dans « beaucoup d'eau », elle monte de 8 sur « -coup ». « Tu as déjà essayé ? » reste plat puis descend de 12 demi-tons sur « essayé » : la question ne monte pas, c'est pourquoi la cible n'est pas « la question monte ».",
      "Transcription : la reconnaissance vocale écrit « verres de farine » pour « vers de farine » (des larves, gusanos de la harina), « la nourrit » pour « la nori », « steak » parfois « stèque », « gaspillé et perdu » pour « gaspillée et perdue ». « Or » (= mais, au début d'une phrase) est un mot de l'écrit : inutile de le faire produire.",
      "Vocabulaire à expliquer si besoin : un grillon, une sauterelle, une chenille, un termite (insectes) ; banal (= normal, ordinaire) ; un défi (= un grand problème à résoudre) ; un tiers (= 1/3)."
    ]
  }
};
